Attribute VB_Name = "SWApiTime"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_CS2TIMESTR(ByVal v_t As Variant, ByVal v_sep As Variant, ByVal v_suppressZero As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CS2TIMESTR = SWApiExecute("swe_cs2timestr", Array(v_t, v_sep, v_suppressZero), options, detail)
End Function

Public Sub SWApiCall10(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_t As Long
    Dim p_sep As Long
    Dim p_suppressZero As Long
    Dim p_a(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    p_t = SWApiInteger(values(0))
    p_sep = SWApiInteger(values(1))
    p_suppressZero = SWApiInteger(values(2))
    nativeResult = Native_swe_cs2timestr(p_t, p_sep, p_suppressZero, p_a(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_a(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_a, "swe_cs2timestr")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "a", SWApiOutputText(p_a, "swe_cs2timestr"), "formatted text", True
    SWApiAdd result, "Input t", values(0), "centiseconds (1/360000 degree)", False
    SWApiAdd result, "Input sep", values(1), "separator character code", False
    SWApiAdd result, "Input suppressZero", values(2), "C boolean 0 or 1", False
End Sub

Public Function SW_SWE_DATE_CONVERSION(ByVal v_y As Variant, ByVal v_m As Variant, ByVal v_d As Variant, ByVal v_utime As Variant, ByVal v_c As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DATE_CONVERSION = SWApiExecute("swe_date_conversion", Array(v_y, v_m, v_d, v_utime, v_c), options, detail)
End Function

Public Sub SWApiCall14(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_y As Long
    Dim p_m As Long
    Dim p_d As Long
    Dim p_utime As Double
    Dim p_c As Byte
    Dim p_tjd(0 To 0) As Double
    Dim nativeResult As Long
    Dim k As Long
    p_y = SWApiInteger(values(0))
    p_m = SWApiInteger(values(1))
    p_d = SWApiInteger(values(2))
    p_utime = SWApiNumber(values(3))
    p_c = SWApiCharacter(values(4))
    nativeResult = Native_swe_date_conversion(p_y, p_m, p_d, p_utime, p_c, p_tjd(0))
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "tjd[" & CStr(k) & "]", p_tjd(k), "Julian day TT or explicitly named input time scale", True
    Next k
    SWApiAdd result, "Input y", values(0), "astronomical year", False
    SWApiAdd result, "Input m", values(1), "month 1..12", False
    SWApiAdd result, "Input d", values(2), "day of month", False
    SWApiAdd result, "Input utime", values(3), "decimal hours", False
    SWApiAdd result, "Input c", values(4), "g Gregorian or j Julian", False
End Sub

Public Function SW_SWE_DAY_OF_WEEK(ByVal v_jd As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DAY_OF_WEEK = SWApiExecute("swe_day_of_week", Array(v_jd), options, detail)
End Function

Public Sub SWApiCall15(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_jd As Double
    Dim nativeResult As Long
    Dim k As Long
    p_jd = SWApiNumber(values(0))
    nativeResult = Native_swe_day_of_week(p_jd)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_day_of_week")
    SWApiAdd result, "Input jd", values(0), "Julian day TT or explicitly named input time scale", False
End Sub

Public Function SW_SWE_DELTAT(ByVal v_tjd As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DELTAT = SWApiExecute("swe_deltat", Array(v_tjd), options, detail)
End Function

Public Sub SWApiCall18(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim nativeResult As Double
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    nativeResult = Native_swe_deltat(p_tjd)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_deltat")
    SWApiAdd result, "Input tjd", values(0), "Julian day TT or explicitly named input time scale", False
End Sub

Public Function SW_SWE_DELTAT_EX(ByVal v_tjd As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DELTAT_EX = SWApiExecute("swe_deltat_ex", Array(v_tjd, v_iflag), options, detail)
End Function

Public Sub SWApiCall19(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_iflag As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_iflag = SWApiInteger(values(1))
    nativeResult = Native_swe_deltat_ex(p_tjd, p_iflag, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_deltat_ex")
    SWApiAdd result, "Input tjd", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_TID_ACC(Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_TID_ACC = SWApiExecute("swe_get_tid_acc", Array(), options, detail)
End Function

Public Sub SWApiCall42(ByRef result As SWApiResult, ByVal values As Variant)
    Dim nativeResult As Double
    Dim k As Long
    nativeResult = Native_swe_get_tid_acc()
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_get_tid_acc")
End Sub

Public Function SW_SWE_JDET_TO_UTC(ByVal v_tjd_et As Variant, ByVal v_gregflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_JDET_TO_UTC = SWApiExecute("swe_jdet_to_utc", Array(v_tjd_et, v_gregflag), options, detail)
End Function

Public Sub SWApiCall55(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim p_gregflag As Long
    Dim p_iyear(0 To 0) As Long
    Dim p_imonth(0 To 0) As Long
    Dim p_iday(0 To 0) As Long
    Dim p_ihour(0 To 0) As Long
    Dim p_imin(0 To 0) As Long
    Dim p_dsec(0 To 0) As Double
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    p_gregflag = SWApiInteger(values(1))
    If p_gregflag <> 0 And p_gregflag <> 1 Then SWRaise "Calendar must be 0 or 1."
    Native_swe_jdet_to_utc p_tjd_et, p_gregflag, p_iyear(0), p_imonth(0), p_iday(0), p_ihour(0), p_imin(0), p_dsec(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "iyear[" & CStr(k) & "]", p_iyear(k), "astronomical year", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imonth[" & CStr(k) & "]", p_imonth(k), "month 1..12", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "iday[" & CStr(k) & "]", p_iday(k), "day of month", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "ihour[" & CStr(k) & "]", p_ihour(k), "hour 0..23", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imin[" & CStr(k) & "]", p_imin(k), "minutes", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dsec[" & CStr(k) & "]", p_dsec(k), "seconds, leap second allowed where documented", True
    Next k
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input gregflag", values(1), "0 Julian, 1 Gregorian", False
End Sub

Public Function SW_SWE_JDUT1_TO_UTC(ByVal v_tjd_ut As Variant, ByVal v_gregflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_JDUT1_TO_UTC = SWApiExecute("swe_jdut1_to_utc", Array(v_tjd_ut, v_gregflag), options, detail)
End Function

Public Sub SWApiCall56(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_gregflag As Long
    Dim p_iyear(0 To 0) As Long
    Dim p_imonth(0 To 0) As Long
    Dim p_iday(0 To 0) As Long
    Dim p_ihour(0 To 0) As Long
    Dim p_imin(0 To 0) As Long
    Dim p_dsec(0 To 0) As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_gregflag = SWApiInteger(values(1))
    If p_gregflag <> 0 And p_gregflag <> 1 Then SWRaise "Calendar must be 0 or 1."
    Native_swe_jdut1_to_utc p_tjd_ut, p_gregflag, p_iyear(0), p_imonth(0), p_iday(0), p_ihour(0), p_imin(0), p_dsec(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "iyear[" & CStr(k) & "]", p_iyear(k), "astronomical year", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imonth[" & CStr(k) & "]", p_imonth(k), "month 1..12", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "iday[" & CStr(k) & "]", p_iday(k), "day of month", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "ihour[" & CStr(k) & "]", p_ihour(k), "hour 0..23", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imin[" & CStr(k) & "]", p_imin(k), "minutes", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dsec[" & CStr(k) & "]", p_dsec(k), "seconds, leap second allowed where documented", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input gregflag", values(1), "0 Julian, 1 Gregorian", False
End Sub

Public Function SW_SWE_JULDAY(ByVal v_year As Variant, ByVal v_month As Variant, ByVal v_day As Variant, ByVal v_hour As Variant, ByVal v_gregflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_JULDAY = SWApiExecute("swe_julday", Array(v_year, v_month, v_day, v_hour, v_gregflag), options, detail)
End Function

Public Sub SWApiCall57(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_year As Long
    Dim p_month As Long
    Dim p_day As Long
    Dim p_hour As Double
    Dim p_gregflag As Long
    Dim nativeResult As Double
    Dim k As Long
    p_year = SWApiInteger(values(0))
    p_month = SWApiInteger(values(1))
    p_day = SWApiInteger(values(2))
    p_hour = SWApiNumber(values(3))
    p_gregflag = SWApiInteger(values(4))
    If p_gregflag <> 0 And p_gregflag <> 1 Then SWRaise "Calendar must be 0 or 1."
    nativeResult = Native_swe_julday(p_year, p_month, p_day, p_hour, p_gregflag)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_julday")
    SWApiAdd result, "Input year", values(0), "astronomical year", False
    SWApiAdd result, "Input month", values(1), "month 1..12", False
    SWApiAdd result, "Input day", values(2), "day of month", False
    SWApiAdd result, "Input hour", values(3), "decimal hours", False
    SWApiAdd result, "Input gregflag", values(4), "0 Julian, 1 Gregorian", False
End Sub

Public Function SW_SWE_LAT_TO_LMT(ByVal v_tjd_lat As Variant, ByVal v_geolon As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LAT_TO_LMT = SWApiExecute("swe_lat_to_lmt", Array(v_tjd_lat, v_geolon), options, detail)
End Function

Public Sub SWApiCall58(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_lat As Double
    Dim p_geolon As Double
    Dim p_tjd_lmt(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_lat = SWApiNumber(values(0))
    p_geolon = SWApiNumber(values(1))
    nativeResult = Native_swe_lat_to_lmt(p_tjd_lat, p_geolon, p_tjd_lmt(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "tjd_lmt[" & CStr(k) & "]", p_tjd_lmt(k), "Julian day TT or explicitly named input time scale", True
    Next k
    SWApiAdd result, "Input tjd_lat", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input geolon", values(1), "degrees east", False
End Sub

Public Function SW_SWE_LMT_TO_LAT(ByVal v_tjd_lmt As Variant, ByVal v_geolon As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LMT_TO_LAT = SWApiExecute("swe_lmt_to_lat", Array(v_tjd_lmt, v_geolon), options, detail)
End Function

Public Sub SWApiCall59(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_lmt As Double
    Dim p_geolon As Double
    Dim p_tjd_lat(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_lmt = SWApiNumber(values(0))
    p_geolon = SWApiNumber(values(1))
    nativeResult = Native_swe_lmt_to_lat(p_tjd_lmt, p_geolon, p_tjd_lat(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "tjd_lat[" & CStr(k) & "]", p_tjd_lat(k), "Julian day TT or explicitly named input time scale", True
    Next k
    SWApiAdd result, "Input tjd_lmt", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input geolon", values(1), "degrees east", False
End Sub

Public Function SW_SWE_REVJUL(ByVal v_jd As Variant, ByVal v_gregflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_REVJUL = SWApiExecute("swe_revjul", Array(v_jd, v_gregflag), options, detail)
End Function

Public Sub SWApiCall79(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_jd As Double
    Dim p_gregflag As Long
    Dim p_jyear(0 To 0) As Long
    Dim p_jmon(0 To 0) As Long
    Dim p_jday(0 To 0) As Long
    Dim p_jut(0 To 0) As Double
    Dim k As Long
    p_jd = SWApiNumber(values(0))
    p_gregflag = SWApiInteger(values(1))
    If p_gregflag <> 0 And p_gregflag <> 1 Then SWRaise "Calendar must be 0 or 1."
    Native_swe_revjul p_jd, p_gregflag, p_jyear(0), p_jmon(0), p_jday(0), p_jut(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "jyear[" & CStr(k) & "]", p_jyear(k), "astronomical year", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "jmon[" & CStr(k) & "]", p_jmon(k), "month 1..12", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "jday[" & CStr(k) & "]", p_jday(k), "day of month", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "jut[" & CStr(k) & "]", p_jut(k), "decimal hours", True
    Next k
    SWApiAdd result, "Input jd", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input gregflag", values(1), "0 Julian, 1 Gregorian", False
End Sub

Public Function SW_SWE_SIDTIME(ByVal v_tjd_ut As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SIDTIME = SWApiExecute("swe_sidtime", Array(v_tjd_ut), options, detail)
End Function

Public Sub SWApiCall91(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim nativeResult As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    nativeResult = Native_swe_sidtime(p_tjd_ut)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_sidtime")
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
End Sub

Public Function SW_SWE_SIDTIME0(ByVal v_tjd_ut As Variant, ByVal v_eps As Variant, ByVal v_nut As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SIDTIME0 = SWApiExecute("swe_sidtime0", Array(v_tjd_ut, v_eps, v_nut), options, detail)
End Function

Public Sub SWApiCall92(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_eps As Double
    Dim p_nut As Double
    Dim nativeResult As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_eps = SWApiNumber(values(1))
    p_nut = SWApiNumber(values(2))
    nativeResult = Native_swe_sidtime0(p_tjd_ut, p_eps, p_nut)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_sidtime0")
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input eps", values(1), "degrees", False
    SWApiAdd result, "Input nut", values(2), "degrees", False
End Sub

Public Function SW_SWE_TIME_EQU(ByVal v_tjd As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_TIME_EQU = SWApiExecute("swe_time_equ", Array(v_tjd), options, detail)
End Function

Public Sub SWApiCall100(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_te(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    nativeResult = Native_swe_time_equ(p_tjd, p_te(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "te[" & CStr(k) & "]", p_te(k), "days (apparent minus mean solar time)", True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day UT1", False
End Sub

Public Function SW_SWE_UTC_TIME_ZONE(ByVal v_iyear As Variant, ByVal v_imonth As Variant, ByVal v_iday As Variant, ByVal v_ihour As Variant, ByVal v_imin As Variant, ByVal v_dsec As Variant, ByVal v_d_timezone As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_UTC_TIME_ZONE = SWApiExecute("swe_utc_time_zone", Array(v_iyear, v_imonth, v_iday, v_ihour, v_imin, v_dsec, v_d_timezone), options, detail)
End Function

Public Sub SWApiCall102(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_iyear As Long
    Dim p_imonth As Long
    Dim p_iday As Long
    Dim p_ihour As Long
    Dim p_imin As Long
    Dim p_dsec As Double
    Dim p_d_timezone As Double
    Dim p_iyear_out(0 To 0) As Long
    Dim p_imonth_out(0 To 0) As Long
    Dim p_iday_out(0 To 0) As Long
    Dim p_ihour_out(0 To 0) As Long
    Dim p_imin_out(0 To 0) As Long
    Dim p_dsec_out(0 To 0) As Double
    Dim k As Long
    p_iyear = SWApiInteger(values(0))
    p_imonth = SWApiInteger(values(1))
    p_iday = SWApiInteger(values(2))
    p_ihour = SWApiInteger(values(3))
    p_imin = SWApiInteger(values(4))
    p_dsec = SWApiNumber(values(5))
    p_d_timezone = SWApiNumber(values(6))
    Native_swe_utc_time_zone p_iyear, p_imonth, p_iday, p_ihour, p_imin, p_dsec, p_d_timezone, p_iyear_out(0), p_imonth_out(0), p_iday_out(0), p_ihour_out(0), p_imin_out(0), p_dsec_out(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "iyear_out[" & CStr(k) & "]", p_iyear_out(k), "astronomical year", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imonth_out[" & CStr(k) & "]", p_imonth_out(k), "month 1..12", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "iday_out[" & CStr(k) & "]", p_iday_out(k), "day of month", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "ihour_out[" & CStr(k) & "]", p_ihour_out(k), "hour 0..23", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imin_out[" & CStr(k) & "]", p_imin_out(k), "minutes", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dsec_out[" & CStr(k) & "]", p_dsec_out(k), "seconds", True
    Next k
    SWApiAdd result, "Input iyear", values(0), "astronomical year", False
    SWApiAdd result, "Input imonth", values(1), "month 1..12", False
    SWApiAdd result, "Input iday", values(2), "day of month", False
    SWApiAdd result, "Input ihour", values(3), "hour 0..23", False
    SWApiAdd result, "Input imin", values(4), "minutes", False
    SWApiAdd result, "Input dsec", values(5), "seconds, leap second allowed where documented", False
    SWApiAdd result, "Input d_timezone", values(6), "hours east of UTC (fractional allowed)", False
End Sub

Public Function SW_SWE_UTC_TO_JD(ByVal v_iyear As Variant, ByVal v_imonth As Variant, ByVal v_iday As Variant, ByVal v_ihour As Variant, ByVal v_imin As Variant, ByVal v_dsec As Variant, ByVal v_gregflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_UTC_TO_JD = SWApiExecute("swe_utc_to_jd", Array(v_iyear, v_imonth, v_iday, v_ihour, v_imin, v_dsec, v_gregflag), options, detail)
End Function

Public Sub SWApiCall103(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_iyear As Long
    Dim p_imonth As Long
    Dim p_iday As Long
    Dim p_ihour As Long
    Dim p_imin As Long
    Dim p_dsec As Double
    Dim p_gregflag As Long
    Dim p_dret(0 To 1) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_iyear = SWApiInteger(values(0))
    p_imonth = SWApiInteger(values(1))
    p_iday = SWApiInteger(values(2))
    p_ihour = SWApiInteger(values(3))
    p_imin = SWApiInteger(values(4))
    p_dsec = SWApiNumber(values(5))
    p_gregflag = SWApiInteger(values(6))
    If p_gregflag <> 0 And p_gregflag <> 1 Then SWRaise "Calendar must be 0 or 1."
    nativeResult = Native_swe_utc_to_jd(p_iyear, p_imonth, p_iday, p_ihour, p_imin, p_dsec, p_gregflag, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 2 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("Julian day TT", "Julian day UT1")(k)), True
    Next k
    SWApiAdd result, "Input iyear", values(0), "astronomical year", False
    SWApiAdd result, "Input imonth", values(1), "month 1..12", False
    SWApiAdd result, "Input iday", values(2), "day of month", False
    SWApiAdd result, "Input ihour", values(3), "hour 0..23", False
    SWApiAdd result, "Input imin", values(4), "minutes", False
    SWApiAdd result, "Input dsec", values(5), "seconds, leap second allowed where documented", False
    SWApiAdd result, "Input gregflag", values(6), "0 Julian, 1 Gregorian", False
End Sub

