Attribute VB_Name = "SWApiHouses"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_GAUQUELIN_SECTOR(ByVal v_t_ut As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_iflag As Variant, ByVal v_imeth As Variant, ByVal v_geopos As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GAUQUELIN_SECTOR = SWApiExecute("swe_gauquelin_sector", Array(v_t_ut, v_ipl, v_starname, v_iflag, v_imeth, v_geopos, v_atpress, v_attemp), options, detail)
End Function

Public Sub SWApiCall31(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_t_ut As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_iflag As Long
    Dim p_imeth As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_dgsect(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_t_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_iflag = SWApiInteger(values(3))
    p_imeth = SWApiInteger(values(4))
    SWApiPutVector p_geopos, values(5), 3
    p_atpress = SWApiNumber(values(6))
    p_attemp = SWApiNumber(values(7))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_gauquelin_sector(p_t_ut, p_ipl, p_starname(0), p_iflag, p_imeth, p_geopos(0), p_atpress, p_attemp, p_dgsect(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "dgsect[" & CStr(k) & "]", p_dgsect(k), "Gauquelin sector 1..36", True
    Next k
    SWApiAdd result, "Input t_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input iflag", values(3), "Swiss flag bit mask", False
    SWApiAdd result, "Input imeth", values(4), "Gauquelin method 0..5", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input atpress", values(6), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(7), "degrees Celsius", False
End Sub

Public Function SW_SWE_HOUSE_NAME(ByVal v_hsys As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSE_NAME = SWApiExecute("swe_house_name", Array(v_hsys), options, detail)
End Function

Public Sub SWApiCall48(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_hsys As Long
    Dim nativeResult As LongPtr
    Dim k As Long
    p_hsys = SWApiCharacter(values(0))
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_house_name(p_hsys)
    result.NativeReturn = nativeResult
    result.NativeReturn = SWApiBorrowedText(nativeResult, 256)
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Name", result.NativeReturn, "text"
    SWApiAdd result, "Input hsys", values(0), "one-character house system", False
End Sub

Public Function SW_SWE_HOUSE_POS(ByVal v_armc As Variant, ByVal v_geolat As Variant, ByVal v_eps As Variant, ByVal v_hsys As Variant, ByVal v_xpin As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSE_POS = SWApiExecute("swe_house_pos", Array(v_armc, v_geolat, v_eps, v_hsys, v_xpin), options, detail)
End Function

Public Sub SWApiCall49(ByRef result As SWApiResult, ByVal values As Variant)
    Dim sunshineCusps(0 To 36) As Double, sunshineAngles(0 To 9) As Double, sunshineStatus As Long
    Dim p_armc As Double
    Dim p_geolat As Double
    Dim p_eps As Double
    Dim p_hsys As Long
    Dim p_xpin(0 To 1) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_armc = SWApiNumber(values(0))
    p_geolat = SWApiNumber(values(1))
    p_eps = SWApiNumber(values(2))
    p_hsys = SWApiCharacter(values(3))
    SWApiPutVector p_xpin, values(4), 2
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    If p_hsys = Asc("I") Or p_hsys = Asc("i") Then
        If IsEmpty(result.SunDeclination) Then SWRaise "Sunshine house position requires sun_declination in options."
        sunshineAngles(9) = CDbl(result.SunDeclination)
        sunshineStatus = Native_swe_houses_armc(p_armc, p_geolat, p_eps, p_hsys, sunshineCusps(0), sunshineAngles(0))
        If sunshineStatus < 0 Then SWRaise "Sunshine reference houses are unavailable."
    End If
    nativeResult = Native_swe_house_pos(p_armc, p_geolat, p_eps, p_hsys, p_xpin(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "house_position", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_house_pos")
    SWApiAdd result, "Input armc", values(0), "degrees", False
    SWApiAdd result, "Input geolat", values(1), "degrees north", False
    SWApiAdd result, "Input eps", values(2), "degrees", False
    SWApiAdd result, "Input hsys", values(3), "one-character house system", False
    For k = 0 To 1
        SWApiAdd result, "Effective input xpin[" & CStr(k) & "]", p_xpin(k), "ecliptic longitude and latitude, degrees", False
    Next k
End Sub

Public Function SW_SWE_HOUSES(ByVal v_tjd_ut As Variant, ByVal v_geolat As Variant, ByVal v_geolon As Variant, ByVal v_hsys As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSES = SWApiExecute("swe_houses", Array(v_tjd_ut, v_geolat, v_geolon, v_hsys), options, detail)
End Function

Public Sub SWApiCall50(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_geolat As Double
    Dim p_geolon As Double
    Dim p_hsys As Long
    Dim p_cusps(0 To 36) As Double
    Dim p_ascmc(0 To 9) As Double
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_geolat = SWApiNumber(values(1))
    p_geolon = SWApiNumber(values(2))
    p_hsys = SWApiCharacter(values(3))
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_houses(p_tjd_ut, p_geolat, p_geolon, p_hsys, p_cusps(0), p_ascmc(0))
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "status", 0#
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusps[" & CStr(k) & "]", p_cusps(k), "degrees (radians with SEFLG_RADIANS); index 1..12 or 1..36 for G", True
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "ascmc[" & CStr(k) & "]", p_ascmc(k), CStr(Array("Ascendant; degrees (radians with SEFLG_RADIANS)", "Midheaven; degrees (radians with SEFLG_RADIANS)", "ARMC; degrees (radians with SEFLG_RADIANS)", "Vertex; degrees (radians with SEFLG_RADIANS)", "equatorial Ascendant; degrees (radians with SEFLG_RADIANS)", "Koch co-Ascendant; degrees (radians with SEFLG_RADIANS)", "Munkasey co-Ascendant; degrees (radians with SEFLG_RADIANS)", "polar Ascendant; degrees (radians with SEFLG_RADIANS)")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input geolat", values(1), "degrees north", False
    SWApiAdd result, "Input geolon", values(2), "degrees east", False
    SWApiAdd result, "Input hsys", values(3), "one-character house system", False
End Sub

Public Function SW_SWE_HOUSES_ARMC(ByVal v_armc As Variant, ByVal v_geolat As Variant, ByVal v_eps As Variant, ByVal v_hsys As Variant, ByVal v_ascmc As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSES_ARMC = SWApiExecute("swe_houses_armc", Array(v_armc, v_geolat, v_eps, v_hsys, v_ascmc), options, detail)
End Function

Public Sub SWApiCall51(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_armc As Double
    Dim p_geolat As Double
    Dim p_eps As Double
    Dim p_hsys As Long
    Dim p_cusps(0 To 36) As Double
    Dim p_ascmc(0 To 9) As Double
    Dim nativeResult As Long
    Dim k As Long
    p_armc = SWApiNumber(values(0))
    p_geolat = SWApiNumber(values(1))
    p_eps = SWApiNumber(values(2))
    p_hsys = SWApiCharacter(values(3))
    SWApiPutVector p_ascmc, values(4), 10
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_houses_armc(p_armc, p_geolat, p_eps, p_hsys, p_cusps(0), p_ascmc(0))
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "status", 0#
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusps[" & CStr(k) & "]", p_cusps(k), "degrees (radians with SEFLG_RADIANS); index 1..12 or 1..36 for G", True
    Next k
    For k = 0 To 10 - 1
        SWApiAdd result, "ascmc[" & CStr(k) & "]", p_ascmc(k), CStr(Array("Ascendant; degrees (radians with SEFLG_RADIANS)", "Midheaven; degrees (radians with SEFLG_RADIANS)", "ARMC; degrees (radians with SEFLG_RADIANS)", "Vertex; degrees (radians with SEFLG_RADIANS)", "equatorial Ascendant; degrees (radians with SEFLG_RADIANS)", "Koch co-Ascendant; degrees (radians with SEFLG_RADIANS)", "Munkasey co-Ascendant; degrees (radians with SEFLG_RADIANS)", "polar Ascendant; degrees (radians with SEFLG_RADIANS)", "reserved; degrees (radians with SEFLG_RADIANS)", "Sun declination (Sunshine ARMC input); degrees (radians with SEFLG_RADIANS)")(k)), True
    Next k
    SWApiAdd result, "Input armc", values(0), "degrees", False
    SWApiAdd result, "Input geolat", values(1), "degrees north", False
    SWApiAdd result, "Input eps", values(2), "degrees", False
    SWApiAdd result, "Input hsys", values(3), "one-character house system", False
    For k = 0 To 9
        SWApiAdd result, "Effective input ascmc[" & CStr(k) & "]", p_ascmc(k), "degrees (radians with SEFLG_RADIANS)", False
    Next k
End Sub

Public Function SW_SWE_HOUSES_ARMC_EX2(ByVal v_armc As Variant, ByVal v_geolat As Variant, ByVal v_eps As Variant, ByVal v_hsys As Variant, ByVal v_ascmc As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSES_ARMC_EX2 = SWApiExecute("swe_houses_armc_ex2", Array(v_armc, v_geolat, v_eps, v_hsys, v_ascmc), options, detail)
End Function

Public Sub SWApiCall52(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_armc As Double
    Dim p_geolat As Double
    Dim p_eps As Double
    Dim p_hsys As Long
    Dim p_cusps(0 To 36) As Double
    Dim p_ascmc(0 To 9) As Double
    Dim p_cusp_speed(0 To 36) As Double
    Dim p_ascmc_speed(0 To 9) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_armc = SWApiNumber(values(0))
    p_geolat = SWApiNumber(values(1))
    p_eps = SWApiNumber(values(2))
    p_hsys = SWApiCharacter(values(3))
    SWApiPutVector p_ascmc, values(4), 10
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_houses_armc_ex2(p_armc, p_geolat, p_eps, p_hsys, p_cusps(0), p_ascmc(0), p_cusp_speed(0), p_ascmc_speed(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusps[" & CStr(k) & "]", p_cusps(k), "degrees (radians with SEFLG_RADIANS); index 1..12 or 1..36 for G", True
    Next k
    For k = 0 To 10 - 1
        SWApiAdd result, "ascmc[" & CStr(k) & "]", p_ascmc(k), CStr(Array("Ascendant; degrees (radians with SEFLG_RADIANS)", "Midheaven; degrees (radians with SEFLG_RADIANS)", "ARMC; degrees (radians with SEFLG_RADIANS)", "Vertex; degrees (radians with SEFLG_RADIANS)", "equatorial Ascendant; degrees (radians with SEFLG_RADIANS)", "Koch co-Ascendant; degrees (radians with SEFLG_RADIANS)", "Munkasey co-Ascendant; degrees (radians with SEFLG_RADIANS)", "polar Ascendant; degrees (radians with SEFLG_RADIANS)", "reserved; degrees (radians with SEFLG_RADIANS)", "Sun declination (Sunshine ARMC input); degrees (radians with SEFLG_RADIANS)")(k)), True
    Next k
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusp_speed[" & CStr(k) & "]", p_cusp_speed(k), "degrees/day (radians/day with SEFLG_RADIANS)", True
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "ascmc_speed[" & CStr(k) & "]", p_ascmc_speed(k), CStr(Array("Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Midheaven daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "ARMC daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Vertex daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "equatorial Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Koch co-Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Munkasey co-Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "polar Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)")(k)), True
    Next k
    SWApiAdd result, "Input armc", values(0), "degrees", False
    SWApiAdd result, "Input geolat", values(1), "degrees north", False
    SWApiAdd result, "Input eps", values(2), "degrees", False
    SWApiAdd result, "Input hsys", values(3), "one-character house system", False
    For k = 0 To 9
        SWApiAdd result, "Effective input ascmc[" & CStr(k) & "]", p_ascmc(k), "degrees (radians with SEFLG_RADIANS)", False
    Next k
End Sub

Public Function SW_SWE_HOUSES_EX(ByVal v_tjd_ut As Variant, ByVal v_iflag As Variant, ByVal v_geolat As Variant, ByVal v_geolon As Variant, ByVal v_hsys As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSES_EX = SWApiExecute("swe_houses_ex", Array(v_tjd_ut, v_iflag, v_geolat, v_geolon, v_hsys), options, detail)
End Function

Public Sub SWApiCall53(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_iflag As Long
    Dim p_geolat As Double
    Dim p_geolon As Double
    Dim p_hsys As Long
    Dim p_cusps(0 To 36) As Double
    Dim p_ascmc(0 To 9) As Double
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_iflag = SWApiInteger(values(1))
    p_geolat = SWApiNumber(values(2))
    p_geolon = SWApiNumber(values(3))
    p_hsys = SWApiCharacter(values(4))
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_houses_ex(p_tjd_ut, p_iflag, p_geolat, p_geolon, p_hsys, p_cusps(0), p_ascmc(0))
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "status", 0#
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusps[" & CStr(k) & "]", p_cusps(k), "degrees (radians with SEFLG_RADIANS); index 1..12 or 1..36 for G", True
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "ascmc[" & CStr(k) & "]", p_ascmc(k), CStr(Array("Ascendant; degrees (radians with SEFLG_RADIANS)", "Midheaven; degrees (radians with SEFLG_RADIANS)", "ARMC; degrees (radians with SEFLG_RADIANS)", "Vertex; degrees (radians with SEFLG_RADIANS)", "equatorial Ascendant; degrees (radians with SEFLG_RADIANS)", "Koch co-Ascendant; degrees (radians with SEFLG_RADIANS)", "Munkasey co-Ascendant; degrees (radians with SEFLG_RADIANS)", "polar Ascendant; degrees (radians with SEFLG_RADIANS)")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
    SWApiAdd result, "Input geolat", values(2), "degrees north", False
    SWApiAdd result, "Input geolon", values(3), "degrees east", False
    SWApiAdd result, "Input hsys", values(4), "one-character house system", False
End Sub

Public Function SW_SWE_HOUSES_EX2(ByVal v_tjd_ut As Variant, ByVal v_iflag As Variant, ByVal v_geolat As Variant, ByVal v_geolon As Variant, ByVal v_hsys As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HOUSES_EX2 = SWApiExecute("swe_houses_ex2", Array(v_tjd_ut, v_iflag, v_geolat, v_geolon, v_hsys), options, detail)
End Function

Public Sub SWApiCall54(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_iflag As Long
    Dim p_geolat As Double
    Dim p_geolon As Double
    Dim p_hsys As Long
    Dim p_cusps(0 To 36) As Double
    Dim p_ascmc(0 To 9) As Double
    Dim p_cusp_speed(0 To 36) As Double
    Dim p_ascmc_speed(0 To 9) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_iflag = SWApiInteger(values(1))
    p_geolat = SWApiNumber(values(2))
    p_geolon = SWApiNumber(values(3))
    p_hsys = SWApiCharacter(values(4))
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    SWApiValidateHouse p_hsys
    nativeResult = Native_swe_houses_ex2(p_tjd_ut, p_iflag, p_geolat, p_geolon, p_hsys, p_cusps(0), p_ascmc(0), p_cusp_speed(0), p_ascmc_speed(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusps[" & CStr(k) & "]", p_cusps(k), "degrees (radians with SEFLG_RADIANS); index 1..12 or 1..36 for G", True
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "ascmc[" & CStr(k) & "]", p_ascmc(k), CStr(Array("Ascendant; degrees (radians with SEFLG_RADIANS)", "Midheaven; degrees (radians with SEFLG_RADIANS)", "ARMC; degrees (radians with SEFLG_RADIANS)", "Vertex; degrees (radians with SEFLG_RADIANS)", "equatorial Ascendant; degrees (radians with SEFLG_RADIANS)", "Koch co-Ascendant; degrees (radians with SEFLG_RADIANS)", "Munkasey co-Ascendant; degrees (radians with SEFLG_RADIANS)", "polar Ascendant; degrees (radians with SEFLG_RADIANS)")(k)), True
    Next k
    For k = 1 To SWApiHouseCount(p_hsys) + 1 - 1
        SWApiAdd result, "cusp_speed[" & CStr(k) & "]", p_cusp_speed(k), "degrees/day (radians/day with SEFLG_RADIANS)", True
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "ascmc_speed[" & CStr(k) & "]", p_ascmc_speed(k), CStr(Array("Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Midheaven daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "ARMC daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Vertex daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "equatorial Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Koch co-Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "Munkasey co-Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)", "polar Ascendant daily speed; degrees/day (radians/day with SEFLG_RADIANS)")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
    SWApiAdd result, "Input geolat", values(2), "degrees north", False
    SWApiAdd result, "Input geolon", values(3), "degrees east", False
    SWApiAdd result, "Input hsys", values(4), "one-character house system", False
End Sub

