Attribute VB_Name = "SWApiConfiguration"
Option Explicit
Option Private Module
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Sub SW_CMD_CLOSE()
    Dim response As Variant
    response = SWApiExecute("swe_close", Array(), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall5(ByRef result As SWApiResult, ByVal values As Variant)
    Dim k As Long
    Native_swe_close
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
End Sub

Public Function SW_CMD_GET_CURRENT_FILE_DATA(ByVal v_ifno As Variant) As Variant
    SW_CMD_GET_CURRENT_FILE_DATA = SWApiExecute("swe_get_current_file_data", Array(v_ifno), Empty, True)
End Function

Public Sub SWApiCall38(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_ifno As Long
    Dim p_tfstart(0 To 0) As Double
    Dim p_tfend(0 To 0) As Double
    Dim p_denum(0 To 0) As Long
    Dim nativeResult As LongPtr
    Dim k As Long
    p_ifno = SWApiInteger(values(0))
    If p_ifno < 0 Or p_ifno > 4 Then SWRaise "File index must be 0..4."
    nativeResult = Native_swe_get_current_file_data(p_ifno, p_tfstart(0), p_tfend(0), p_denum(0))
    result.NativeReturn = nativeResult
    result.NativeReturn = SWApiBorrowedText(nativeResult, 256)
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Name", result.NativeReturn, "text"
    For k = 0 To 1 - 1
        SWApiAdd result, "tfstart[" & CStr(k) & "]", p_tfstart(k), "Julian day TT", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "tfend[" & CStr(k) & "]", p_tfend(k), "Julian day TT", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "denum[" & CStr(k) & "]", p_denum(k), "JPL DE number", True
    Next k
    SWApiAdd result, "Input ifno", values(0), "file slot 0..4", False
End Sub

Public Sub SW_CMD_SET_ASTRO_MODELS(ByVal v_samod As Variant, ByVal v_iflag As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_astro_models", Array(v_samod, v_iflag), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall82(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_samod(0 To 255) As Byte
    Dim p_iflag As Long
    Dim k As Long
    SWApiPutText p_samod, CStr(values(0))
    p_iflag = SWApiInteger(values(1))
    SWApiValidateModels SWBufferText(p_samod)
    Native_swe_set_astro_models p_samod(0), p_iflag
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input samod", values(0), "experimental astronomical model/version specification", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
End Sub

Public Sub SW_CMD_SET_DELTA_T_USERDEF(ByVal v_dt As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_delta_t_userdef", Array(v_dt), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall83(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_dt As Double
    Dim k As Long
    p_dt = SWApiNumber(values(0))
    Native_swe_set_delta_t_userdef p_dt
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input dt", values(0), "days; automatic sentinel -1e-10", False
End Sub

Public Sub SW_CMD_SET_EPHE_PATH(ByVal v_path As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_ephe_path", Array(v_path), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall84(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_path(0 To 255) As Byte
    Dim k As Long
    SWApiPutText p_path, CStr(values(0))
    Native_swe_set_ephe_path p_path(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input path", values(0), "absolute directory or path list, Windows ANSI encoding", False
End Sub

Public Sub SW_CMD_SET_INTERPOLATE_NUT(ByVal v_do_interpolate As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_interpolate_nut", Array(v_do_interpolate), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall85(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_do_interpolate As Long
    Dim k As Long
    p_do_interpolate = SWApiInteger(values(0))
    Native_swe_set_interpolate_nut p_do_interpolate
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input do_interpolate", values(0), "C boolean 0 or 1", False
End Sub

Public Sub SW_CMD_SET_JPL_FILE(ByVal v_fname As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_jpl_file", Array(v_fname), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall86(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_fname(0 To 255) As Byte
    Dim k As Long
    SWApiPutText p_fname, CStr(values(0))
    Native_swe_set_jpl_file p_fname(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input fname", values(0), "JPL filename relative to configured data path", False
End Sub

Public Sub SW_CMD_SET_LAPSE_RATE(ByVal v_lapse_rate As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_lapse_rate", Array(v_lapse_rate), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall87(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_lapse_rate As Double
    Dim k As Long
    p_lapse_rate = SWApiNumber(values(0))
    Native_swe_set_lapse_rate p_lapse_rate
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input lapse_rate", values(0), "kelvin/metre", False
End Sub

Public Sub SW_CMD_SET_SID_MODE(ByVal v_sid_mode As Variant, ByVal v_t0 As Variant, ByVal v_ayan_t0 As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_sid_mode", Array(v_sid_mode, v_t0, v_ayan_t0), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall88(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_sid_mode As Long
    Dim p_t0 As Double
    Dim p_ayan_t0 As Double
    Dim k As Long
    p_sid_mode = SWApiInteger(values(0))
    p_t0 = SWApiNumber(values(1))
    p_ayan_t0 = SWApiNumber(values(2))
    Native_swe_set_sid_mode p_sid_mode, p_t0, p_ayan_t0
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input sid_mode", values(0), "sidereal mode ID and modifier bits; 255 user defined", False
    SWApiAdd result, "Input t0", values(1), "reference Julian day TT unless sidereal modifier changes it", False
    SWApiAdd result, "Input ayan_t0", values(2), "degrees", False
End Sub

Public Sub SW_CMD_SET_TID_ACC(ByVal v_t_acc As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_tid_acc", Array(v_t_acc), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall89(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_t_acc As Double
    Dim k As Long
    p_t_acc = SWApiNumber(values(0))
    Native_swe_set_tid_acc p_t_acc
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input t_acc", values(0), "arcseconds/century squared; automatic sentinel 999999", False
End Sub

Public Sub SW_CMD_SET_TOPO(ByVal v_geolon As Variant, ByVal v_geolat As Variant, ByVal v_geoalt As Variant)
    Dim response As Variant
    response = SWApiExecute("swe_set_topo", Array(v_geolon, v_geolat, v_geoalt), Empty, True)
    If response(2, 2) <> "OK" Then SWRaise CStr(response(3, 2))
End Sub

Public Sub SWApiCall90(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_geolon As Double
    Dim p_geolat As Double
    Dim p_geoalt As Double
    Dim k As Long
    p_geolon = SWApiNumber(values(0))
    p_geolat = SWApiNumber(values(1))
    p_geoalt = SWApiNumber(values(2))
    If Abs(p_geolat) > 90# Then SWRaise "Latitude must be within -90..90 degrees."
    Native_swe_set_topo p_geolon, p_geolat, p_geoalt
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Input geolon", values(0), "degrees east", False
    SWApiAdd result, "Input geolat", values(1), "degrees north", False
    SWApiAdd result, "Input geoalt", values(2), "metres", False
End Sub

