Attribute VB_Name = "SWApiPositions"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_CALC(ByVal v_tjd As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CALC = SWApiExecute("swe_calc", Array(v_tjd, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall2(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_calc(p_tjd, p_ipl, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_CALC_PCTR(ByVal v_tjd As Variant, ByVal v_ipl As Variant, ByVal v_iplctr As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CALC_PCTR = SWApiExecute("swe_calc_pctr", Array(v_tjd, v_ipl, v_iplctr, v_iflag), options, detail)
End Function

Public Sub SWApiCall3(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ipl As Long
    Dim p_iplctr As Long
    Dim p_iflag As Long
    Dim p_xxret(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iplctr = SWApiInteger(values(2))
    p_iflag = SWApiInteger(values(3))
    nativeResult = Native_swe_calc_pctr(p_tjd, p_ipl, p_iplctr, p_iflag, p_xxret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    For k = 0 To 6 - 1
        SWApiAdd result, "xxret[" & CStr(k) & "]", p_xxret(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iplctr", values(2), "Swiss centre body ID", False
    SWApiAdd result, "Input iflag", values(3), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_CALC_UT(ByVal v_tjd_ut As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CALC_UT = SWApiExecute("swe_calc_ut", Array(v_tjd_ut, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall4(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_calc_ut(p_tjd_ut, p_ipl, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_AYANAMSA(ByVal v_tjd_et As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_AYANAMSA = SWApiExecute("swe_get_ayanamsa", Array(v_tjd_et), options, detail)
End Function

Public Sub SWApiCall33(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim nativeResult As Double
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    nativeResult = Native_swe_get_ayanamsa(p_tjd_et)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_get_ayanamsa")
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
End Sub

Public Function SW_SWE_GET_AYANAMSA_EX(ByVal v_tjd_et As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_AYANAMSA_EX = SWApiExecute("swe_get_ayanamsa_ex", Array(v_tjd_et, v_iflag), options, detail)
End Function

Public Sub SWApiCall34(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim p_iflag As Long
    Dim p_daya(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    p_iflag = SWApiInteger(values(1))
    nativeResult = Native_swe_get_ayanamsa_ex(p_tjd_et, p_iflag, p_daya(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    For k = 0 To 1 - 1
        SWApiAdd result, "daya[" & CStr(k) & "]", p_daya(k), "degrees", True
    Next k
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_AYANAMSA_EX_UT(ByVal v_tjd_ut As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_AYANAMSA_EX_UT = SWApiExecute("swe_get_ayanamsa_ex_ut", Array(v_tjd_ut, v_iflag), options, detail)
End Function

Public Sub SWApiCall35(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_iflag As Long
    Dim p_daya(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_iflag = SWApiInteger(values(1))
    nativeResult = Native_swe_get_ayanamsa_ex_ut(p_tjd_ut, p_iflag, p_daya(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    For k = 0 To 1 - 1
        SWApiAdd result, "daya[" & CStr(k) & "]", p_daya(k), "degrees", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_AYANAMSA_NAME(ByVal v_isidmode As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_AYANAMSA_NAME = SWApiExecute("swe_get_ayanamsa_name", Array(v_isidmode), options, detail)
End Function

Public Sub SWApiCall36(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_isidmode As Long
    Dim nativeResult As LongPtr
    Dim k As Long
    p_isidmode = SWApiInteger(values(0))
    nativeResult = Native_swe_get_ayanamsa_name(p_isidmode)
    result.NativeReturn = nativeResult
    result.NativeReturn = SWApiBorrowedText(nativeResult, 256)
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Name", result.NativeReturn, "text"
    SWApiAdd result, "Input isidmode", values(0), "built-in sidereal ID 0..46", False
End Sub

Public Function SW_SWE_GET_AYANAMSA_UT(ByVal v_tjd_ut As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_AYANAMSA_UT = SWApiExecute("swe_get_ayanamsa_ut", Array(v_tjd_ut), options, detail)
End Function

Public Sub SWApiCall37(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim nativeResult As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    nativeResult = Native_swe_get_ayanamsa_ut(p_tjd_ut)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_get_ayanamsa_ut")
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
End Sub

Public Function SW_SWE_GET_ORBITAL_ELEMENTS(ByVal v_tjd_et As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_ORBITAL_ELEMENTS = SWApiExecute("swe_get_orbital_elements", Array(v_tjd_et, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall40(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_dret(0 To 49) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_get_orbital_elements(p_tjd_et, p_ipl, p_iflag, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 17 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("semimajor axis AU", "eccentricity", "inclination degrees", "ascending node degrees", "argument of perihelion degrees", "longitude of perihelion degrees", "mean anomaly degrees", "true anomaly degrees", "eccentric anomaly degrees", "mean longitude degrees", "sidereal period tropical years", "mean daily motion degrees/day", "tropical period years", "synodic period days", "perihelion epoch JD TT", "perihelion distance AU", "aphelion distance AU")(k)), True
    Next k
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_PLANET_NAME(ByVal v_ipl As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_PLANET_NAME = SWApiExecute("swe_get_planet_name", Array(v_ipl), options, detail)
End Function

Public Sub SWApiCall41(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_ipl As Long
    Dim p_spname(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    p_ipl = SWApiInteger(values(0))
    nativeResult = Native_swe_get_planet_name(p_ipl, p_spname(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_spname(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_spname, "swe_get_planet_name")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "spname", SWApiOutputText(p_spname, "swe_get_planet_name"), "body name", True
    SWApiAdd result, "Input ipl", values(0), "Swiss body ID", False
End Sub

Public Function SW_SWE_NOD_APS(ByVal v_tjd_et As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, ByVal v_method As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_NOD_APS = SWApiExecute("swe_nod_aps", Array(v_tjd_et, v_ipl, v_iflag, v_method), options, detail)
End Function

Public Sub SWApiCall70(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_method As Long
    Dim p_xnasc(0 To 5) As Double
    Dim p_xndsc(0 To 5) As Double
    Dim p_xperi(0 To 5) As Double
    Dim p_xaphe(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    p_method = SWApiInteger(values(3))
    nativeResult = Native_swe_nod_aps(p_tjd_et, p_ipl, p_iflag, p_method, p_xnasc(0), p_xndsc(0), p_xperi(0), p_xaphe(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 6 - 1
        SWApiAdd result, "xnasc[" & CStr(k) & "]", p_xnasc(k), "ascending node coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xndsc[" & CStr(k) & "]", p_xndsc(k), "descending node coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xperi[" & CStr(k) & "]", p_xperi(k), "periapsis coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xaphe[" & CStr(k) & "]", p_xaphe(k), "apoapsis/focal-point coordinates and speeds, selected by flags", True
    Next k
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
    SWApiAdd result, "Input method", values(3), "node/apsis method bit mask", False
End Sub

Public Function SW_SWE_NOD_APS_UT(ByVal v_tjd_ut As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, ByVal v_method As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_NOD_APS_UT = SWApiExecute("swe_nod_aps_ut", Array(v_tjd_ut, v_ipl, v_iflag, v_method), options, detail)
End Function

Public Sub SWApiCall71(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_method As Long
    Dim p_xnasc(0 To 5) As Double
    Dim p_xndsc(0 To 5) As Double
    Dim p_xperi(0 To 5) As Double
    Dim p_xaphe(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    p_method = SWApiInteger(values(3))
    nativeResult = Native_swe_nod_aps_ut(p_tjd_ut, p_ipl, p_iflag, p_method, p_xnasc(0), p_xndsc(0), p_xperi(0), p_xaphe(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 6 - 1
        SWApiAdd result, "xnasc[" & CStr(k) & "]", p_xnasc(k), "ascending node coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xndsc[" & CStr(k) & "]", p_xndsc(k), "descending node coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xperi[" & CStr(k) & "]", p_xperi(k), "periapsis coordinates and speeds, selected by flags", True
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "xaphe[" & CStr(k) & "]", p_xaphe(k), "apoapsis/focal-point coordinates and speeds, selected by flags", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
    SWApiAdd result, "Input method", values(3), "node/apsis method bit mask", False
End Sub

Public Function SW_SWE_ORBIT_MAX_MIN_TRUE_DISTANCE(ByVal v_tjd_et As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_ORBIT_MAX_MIN_TRUE_DISTANCE = SWApiExecute("swe_orbit_max_min_true_distance", Array(v_tjd_et, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall72(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_et As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_dmax(0 To 0) As Double
    Dim p_dmin(0 To 0) As Double
    Dim p_dtrue(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_et = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_orbit_max_min_true_distance(p_tjd_et, p_ipl, p_iflag, p_dmax(0), p_dmin(0), p_dtrue(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "dmax[" & CStr(k) & "]", p_dmax(k), "AU", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dmin[" & CStr(k) & "]", p_dmin(k), "AU", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dtrue[" & CStr(k) & "]", p_dtrue(k), "AU", True
    Next k
    SWApiAdd result, "Input tjd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_PHENO(ByVal v_tjd As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_PHENO = SWApiExecute("swe_pheno", Array(v_tjd, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall73(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_pheno(p_tjd, p_ipl, p_iflag, p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 6 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("phase angle degrees", "illuminated fraction", "elongation degrees", "apparent diameter degrees", "apparent magnitude", "horizontal parallax degrees (Moon)")(k)), True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_PHENO_UT(ByVal v_tjd_ut As Variant, ByVal v_ipl As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_PHENO_UT = SWApiExecute("swe_pheno_ut", Array(v_tjd_ut, v_ipl, v_iflag), options, detail)
End Function

Public Sub SWApiCall74(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ipl As Long
    Dim p_iflag As Long
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_pheno_ut(p_tjd_ut, p_ipl, p_iflag, p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 6 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("phase angle degrees", "illuminated fraction", "elongation degrees", "apparent diameter degrees", "apparent magnitude", "horizontal parallax degrees (Moon)")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

