Attribute VB_Name = "SWApiUtilities"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_AZALT(ByVal v_tjd_ut As Variant, ByVal v_calc_flag As Variant, ByVal v_geopos As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, ByVal v_xin As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_AZALT = SWApiExecute("swe_azalt", Array(v_tjd_ut, v_calc_flag, v_geopos, v_atpress, v_attemp, v_xin), options, detail)
End Function

Public Sub SWApiCall0(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_calc_flag As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_xin(0 To 2) As Double
    Dim p_xaz(0 To 2) As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_calc_flag = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    p_atpress = SWApiNumber(values(3))
    p_attemp = SWApiNumber(values(4))
    SWApiPutVector p_xin, values(5), 3
    SWApiValidateObserver p_geopos
    Native_swe_azalt p_tjd_ut, p_calc_flag, p_geopos(0), p_atpress, p_attemp, p_xin(0), p_xaz(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 3 - 1
        SWApiAdd result, "xaz[" & CStr(k) & "]", p_xaz(k), CStr(Array("azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input calc_flag", values(1), "coordinate/refraction mode code", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input atpress", values(3), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(4), "degrees Celsius", False
    For k = 0 To 2
        SWApiAdd result, "Effective input xin[" & CStr(k) & "]", p_xin(k), "coordinates selected by calc_flag, degrees; optional radius", False
    Next k
End Sub

Public Function SW_SWE_AZALT_REV(ByVal v_tjd_ut As Variant, ByVal v_calc_flag As Variant, ByVal v_geopos As Variant, ByVal v_xin As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_AZALT_REV = SWApiExecute("swe_azalt_rev", Array(v_tjd_ut, v_calc_flag, v_geopos, v_xin), options, detail)
End Function

Public Sub SWApiCall1(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_calc_flag As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_xin(0 To 1) As Double
    Dim p_xout(0 To 1) As Double
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_calc_flag = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    SWApiPutVector p_xin, values(3), 2
    SWApiValidateObserver p_geopos
    Native_swe_azalt_rev p_tjd_ut, p_calc_flag, p_geopos(0), p_xin(0), p_xout(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 2 - 1
        SWApiAdd result, "xout[" & CStr(k) & "]", p_xout(k), "longitude/right ascension; latitude/declination, degrees", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input calc_flag", values(1), "coordinate/refraction mode code", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 1
        SWApiAdd result, "Effective input xin[" & CStr(k) & "]", p_xin(k), "coordinates selected by calc_flag, degrees; optional radius", False
    Next k
End Sub

Public Function SW_SWE_COTRANS(ByVal v_xpo As Variant, ByVal v_eps As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_COTRANS = SWApiExecute("swe_cotrans", Array(v_xpo, v_eps), options, detail)
End Function

Public Sub SWApiCall6(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_xpo(0 To 2) As Double
    Dim p_xpn(0 To 2) As Double
    Dim p_eps As Double
    Dim k As Long
    SWApiPutVector p_xpo, values(0), 3
    p_eps = SWApiNumber(values(1))
    Native_swe_cotrans p_xpo(0), p_xpn(0), p_eps
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 3 - 1
        SWApiAdd result, "xpn[" & CStr(k) & "]", p_xpn(k), "longitude/latitude degrees; radius; optional matching daily speeds", True
    Next k
    For k = 0 To 2
        SWApiAdd result, "Effective input xpo[" & CStr(k) & "]", p_xpo(k), "longitude/latitude degrees; radius; optional matching daily speeds", False
    Next k
    SWApiAdd result, "Input eps", values(1), "degrees", False
End Sub

Public Function SW_SWE_COTRANS_SP(ByVal v_xpo As Variant, ByVal v_eps As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_COTRANS_SP = SWApiExecute("swe_cotrans_sp", Array(v_xpo, v_eps), options, detail)
End Function

Public Sub SWApiCall7(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_xpo(0 To 5) As Double
    Dim p_xpn(0 To 5) As Double
    Dim p_eps As Double
    Dim k As Long
    SWApiPutVector p_xpo, values(0), 6
    p_eps = SWApiNumber(values(1))
    Native_swe_cotrans_sp p_xpo(0), p_xpn(0), p_eps
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 6 - 1
        SWApiAdd result, "xpn[" & CStr(k) & "]", p_xpn(k), "longitude/latitude degrees; radius; optional matching daily speeds", True
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input xpo[" & CStr(k) & "]", p_xpo(k), "longitude/latitude degrees; radius; optional matching daily speeds", False
    Next k
    SWApiAdd result, "Input eps", values(1), "degrees", False
End Sub

Public Function SW_SWE_CS2DEGSTR(ByVal v_t As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CS2DEGSTR = SWApiExecute("swe_cs2degstr", Array(v_t), options, detail)
End Function

Public Sub SWApiCall8(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_t As Long
    Dim p_a(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    p_t = SWApiInteger(values(0))
    nativeResult = Native_swe_cs2degstr(p_t, p_a(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_a(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_a, "swe_cs2degstr")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "a", SWApiOutputText(p_a, "swe_cs2degstr"), "formatted text", True
    SWApiAdd result, "Input t", values(0), "centiseconds (1/360000 degree)", False
End Sub

Public Function SW_SWE_CS2LONLATSTR(ByVal v_t As Variant, ByVal v_pchar As Variant, ByVal v_mchar As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CS2LONLATSTR = SWApiExecute("swe_cs2lonlatstr", Array(v_t, v_pchar, v_mchar), options, detail)
End Function

Public Sub SWApiCall9(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_t As Long
    Dim p_pchar As Byte
    Dim p_mchar As Byte
    Dim p_s(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    p_t = SWApiInteger(values(0))
    p_pchar = SWApiCharacter(values(1))
    p_mchar = SWApiCharacter(values(2))
    nativeResult = Native_swe_cs2lonlatstr(p_t, p_pchar, p_mchar, p_s(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_s(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_s, "swe_cs2lonlatstr")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "s", SWApiOutputText(p_s, "swe_cs2lonlatstr"), "formatted text", True
    SWApiAdd result, "Input t", values(0), "centiseconds (1/360000 degree)", False
    SWApiAdd result, "Input pchar", values(1), "positive hemisphere character", False
    SWApiAdd result, "Input mchar", values(2), "negative hemisphere character", False
End Sub

Public Function SW_SWE_CSNORM(ByVal v_p As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CSNORM = SWApiExecute("swe_csnorm", Array(v_p), options, detail)
End Function

Public Sub SWApiCall11(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p As Long
    Dim nativeResult As Long
    Dim k As Long
    p_p = SWApiInteger(values(0))
    nativeResult = Native_swe_csnorm(p_p)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_csnorm")
    SWApiAdd result, "Input p", values(0), "centiseconds (1/360000 degree)", False
End Sub

Public Function SW_SWE_CSROUNDSEC(ByVal v_x As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_CSROUNDSEC = SWApiExecute("swe_csroundsec", Array(v_x), options, detail)
End Function

Public Sub SWApiCall12(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x As Long
    Dim nativeResult As Long
    Dim k As Long
    p_x = SWApiInteger(values(0))
    nativeResult = Native_swe_csroundsec(p_x)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_csroundsec")
    SWApiAdd result, "Input x", values(0), "centiseconds (1/360000 degree)", False
End Sub

Public Function SW_SWE_D2L(ByVal v_x As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_D2L = SWApiExecute("swe_d2l", Array(v_x), options, detail)
End Function

Public Sub SWApiCall13(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x As Double
    Dim nativeResult As Long
    Dim k As Long
    p_x = SWApiNumber(values(0))
    nativeResult = Native_swe_d2l(p_x)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_d2l")
    SWApiAdd result, "Input x", values(0), "degrees", False
End Sub

Public Function SW_SWE_DEG_MIDP(ByVal v_x1 As Variant, ByVal v_x0 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DEG_MIDP = SWApiExecute("swe_deg_midp", Array(v_x1, v_x0), options, detail)
End Function

Public Sub SWApiCall16(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x1 As Double
    Dim p_x0 As Double
    Dim nativeResult As Double
    Dim k As Long
    p_x1 = SWApiNumber(values(0))
    p_x0 = SWApiNumber(values(1))
    nativeResult = Native_swe_deg_midp(p_x1, p_x0)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_deg_midp")
    SWApiAdd result, "Input x1", values(0), "degrees", False
    SWApiAdd result, "Input x0", values(1), "degrees", False
End Sub

Public Function SW_SWE_DEGNORM(ByVal v_x As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DEGNORM = SWApiExecute("swe_degnorm", Array(v_x), options, detail)
End Function

Public Sub SWApiCall17(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x As Double
    Dim nativeResult As Double
    Dim k As Long
    p_x = SWApiNumber(values(0))
    nativeResult = Native_swe_degnorm(p_x)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_degnorm")
    SWApiAdd result, "Input x", values(0), "degrees", False
End Sub

Public Function SW_SWE_DIFCS2N(ByVal v_p1 As Variant, ByVal v_p2 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DIFCS2N = SWApiExecute("swe_difcs2n", Array(v_p1, v_p2), options, detail)
End Function

Public Sub SWApiCall20(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p1 As Long
    Dim p_p2 As Long
    Dim nativeResult As Long
    Dim k As Long
    p_p1 = SWApiInteger(values(0))
    p_p2 = SWApiInteger(values(1))
    nativeResult = Native_swe_difcs2n(p_p1, p_p2)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_difcs2n")
    SWApiAdd result, "Input p1", values(0), "centiseconds (1/360000 degree)", False
    SWApiAdd result, "Input p2", values(1), "centiseconds (1/360000 degree)", False
End Sub

Public Function SW_SWE_DIFCSN(ByVal v_p1 As Variant, ByVal v_p2 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DIFCSN = SWApiExecute("swe_difcsn", Array(v_p1, v_p2), options, detail)
End Function

Public Sub SWApiCall21(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p1 As Long
    Dim p_p2 As Long
    Dim nativeResult As Long
    Dim k As Long
    p_p1 = SWApiInteger(values(0))
    p_p2 = SWApiInteger(values(1))
    nativeResult = Native_swe_difcsn(p_p1, p_p2)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "signed", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_difcsn")
    SWApiAdd result, "Input p1", values(0), "centiseconds (1/360000 degree)", False
    SWApiAdd result, "Input p2", values(1), "centiseconds (1/360000 degree)", False
End Sub

Public Function SW_SWE_DIFDEG2N(ByVal v_p1 As Variant, ByVal v_p2 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DIFDEG2N = SWApiExecute("swe_difdeg2n", Array(v_p1, v_p2), options, detail)
End Function

Public Sub SWApiCall22(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p1 As Double
    Dim p_p2 As Double
    Dim nativeResult As Double
    Dim k As Long
    p_p1 = SWApiNumber(values(0))
    p_p2 = SWApiNumber(values(1))
    nativeResult = Native_swe_difdeg2n(p_p1, p_p2)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_difdeg2n")
    SWApiAdd result, "Input p1", values(0), "degrees", False
    SWApiAdd result, "Input p2", values(1), "degrees", False
End Sub

Public Function SW_SWE_DIFDEGN(ByVal v_p1 As Variant, ByVal v_p2 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DIFDEGN = SWApiExecute("swe_difdegn", Array(v_p1, v_p2), options, detail)
End Function

Public Sub SWApiCall23(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p1 As Double
    Dim p_p2 As Double
    Dim nativeResult As Double
    Dim k As Long
    p_p1 = SWApiNumber(values(0))
    p_p2 = SWApiNumber(values(1))
    nativeResult = Native_swe_difdegn(p_p1, p_p2)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_difdegn")
    SWApiAdd result, "Input p1", values(0), "degrees", False
    SWApiAdd result, "Input p2", values(1), "degrees", False
End Sub

Public Function SW_SWE_DIFRAD2N(ByVal v_p1 As Variant, ByVal v_p2 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_DIFRAD2N = SWApiExecute("swe_difrad2n", Array(v_p1, v_p2), options, detail)
End Function

Public Sub SWApiCall24(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_p1 As Double
    Dim p_p2 As Double
    Dim nativeResult As Double
    Dim k As Long
    p_p1 = SWApiNumber(values(0))
    p_p2 = SWApiNumber(values(1))
    nativeResult = Native_swe_difrad2n(p_p1, p_p2)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_difrad2n")
    SWApiAdd result, "Input p1", values(0), "radians", False
    SWApiAdd result, "Input p2", values(1), "radians", False
End Sub

Public Function SW_SWE_GET_ASTRO_MODELS(ByVal v_samod As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_ASTRO_MODELS = SWApiExecute("swe_get_astro_models", Array(v_samod, v_iflag), options, detail)
End Function

Public Sub SWApiCall32(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_samod(0 To 255) As Byte
    Dim p_sdet(0 To 16383) As Byte
    Dim p_iflag As Long
    Dim k As Long
    SWApiPutText p_samod, CStr(values(0))
    p_iflag = SWApiInteger(values(1))
    SWApiValidateModels SWBufferText(p_samod)
    Native_swe_get_astro_models p_samod(0), p_sdet(0), p_iflag
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "sdet", SWApiOutputText(p_sdet, "swe_get_astro_models"), "experimental model-description text", True
    SWApiAdd result, "Input samod", values(0), "experimental astronomical model/version specification", False
    SWApiAdd result, "Input iflag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_GET_LIBRARY_PATH(Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_GET_LIBRARY_PATH = SWApiExecute("swe_get_library_path", Array(), options, detail)
End Function

Public Sub SWApiCall39(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_arg1(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    nativeResult = Native_swe_get_library_path(p_arg1(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_arg1(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_arg1, "swe_get_library_path")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "arg1", SWApiOutputText(p_arg1, "swe_get_library_path"), "NUL-terminated string", True
End Sub

Public Function SW_SWE_RAD_MIDP(ByVal v_x1 As Variant, ByVal v_x0 As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_RAD_MIDP = SWApiExecute("swe_rad_midp", Array(v_x1, v_x0), options, detail)
End Function

Public Sub SWApiCall75(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x1 As Double
    Dim p_x0 As Double
    Dim nativeResult As Double
    Dim k As Long
    p_x1 = SWApiNumber(values(0))
    p_x0 = SWApiNumber(values(1))
    nativeResult = Native_swe_rad_midp(p_x1, p_x0)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_rad_midp")
    SWApiAdd result, "Input x1", values(0), "radians", False
    SWApiAdd result, "Input x0", values(1), "radians", False
End Sub

Public Function SW_SWE_RADNORM(ByVal v_x As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_RADNORM = SWApiExecute("swe_radnorm", Array(v_x), options, detail)
End Function

Public Sub SWApiCall76(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x As Double
    Dim nativeResult As Double
    Dim k As Long
    p_x = SWApiNumber(values(0))
    nativeResult = Native_swe_radnorm(p_x)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_radnorm")
    SWApiAdd result, "Input x", values(0), "radians", False
End Sub

Public Function SW_SWE_REFRAC(ByVal v_inalt As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, ByVal v_calc_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_REFRAC = SWApiExecute("swe_refrac", Array(v_inalt, v_atpress, v_attemp, v_calc_flag), options, detail)
End Function

Public Sub SWApiCall77(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_inalt As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_calc_flag As Long
    Dim nativeResult As Double
    Dim k As Long
    p_inalt = SWApiNumber(values(0))
    p_atpress = SWApiNumber(values(1))
    p_attemp = SWApiNumber(values(2))
    p_calc_flag = SWApiInteger(values(3))
    nativeResult = Native_swe_refrac(p_inalt, p_atpress, p_attemp, p_calc_flag)
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_refrac")
    SWApiAdd result, "Input inalt", values(0), "altitude degrees", False
    SWApiAdd result, "Input atpress", values(1), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(2), "degrees Celsius", False
    SWApiAdd result, "Input calc_flag", values(3), "coordinate/refraction mode code", False
End Sub

Public Function SW_SWE_REFRAC_EXTENDED(ByVal v_inalt As Variant, ByVal v_geoalt As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, ByVal v_lapse_rate As Variant, ByVal v_calc_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_REFRAC_EXTENDED = SWApiExecute("swe_refrac_extended", Array(v_inalt, v_geoalt, v_atpress, v_attemp, v_lapse_rate, v_calc_flag), options, detail)
End Function

Public Sub SWApiCall78(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_inalt As Double
    Dim p_geoalt As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_lapse_rate As Double
    Dim p_calc_flag As Long
    Dim p_dret(0 To 3) As Double
    Dim nativeResult As Double
    Dim k As Long
    p_inalt = SWApiNumber(values(0))
    p_geoalt = SWApiNumber(values(1))
    p_atpress = SWApiNumber(values(2))
    p_attemp = SWApiNumber(values(3))
    p_lapse_rate = SWApiNumber(values(4))
    p_calc_flag = SWApiInteger(values(5))
    nativeResult = Native_swe_refrac_extended(p_inalt, p_geoalt, p_atpress, p_attemp, p_lapse_rate, p_calc_flag, p_dret(0))
    result.NativeReturn = nativeResult
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_refrac_extended")
    For k = 0 To 4 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("true altitude degrees", "apparent altitude degrees", "refraction degrees", "horizon dip degrees")(k)), True
    Next k
    SWApiAdd result, "Input inalt", values(0), "altitude degrees", False
    SWApiAdd result, "Input geoalt", values(1), "metres", False
    SWApiAdd result, "Input atpress", values(2), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(3), "degrees Celsius", False
    SWApiAdd result, "Input lapse_rate", values(4), "kelvin/metre", False
    SWApiAdd result, "Input calc_flag", values(5), "coordinate/refraction mode code", False
End Sub

Public Function SW_SWE_SPLIT_DEG(ByVal v_ddeg As Variant, ByVal v_roundflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SPLIT_DEG = SWApiExecute("swe_split_deg", Array(v_ddeg, v_roundflag), options, detail)
End Function

Public Sub SWApiCall99(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_ddeg As Double
    Dim p_roundflag As Long
    Dim p_ideg(0 To 0) As Long
    Dim p_imin(0 To 0) As Long
    Dim p_isec(0 To 0) As Long
    Dim p_dsecfr(0 To 0) As Double
    Dim p_isgn(0 To 0) As Long
    Dim k As Long
    p_ddeg = SWApiNumber(values(0))
    p_roundflag = SWApiInteger(values(1))
    Native_swe_split_deg p_ddeg, p_roundflag, p_ideg(0), p_imin(0), p_isec(0), p_dsecfr(0), p_isgn(0)
    result.NativeReturn = 0
    SWApiCheckReturn result, "value", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "ideg[" & CStr(k) & "]", p_ideg(k), "whole degrees", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "imin[" & CStr(k) & "]", p_imin(k), "minutes", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "isec[" & CStr(k) & "]", p_isec(k), "arcseconds", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dsecfr[" & CStr(k) & "]", p_dsecfr(k), "fractional arcsecond", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "isgn[" & CStr(k) & "]", p_isgn(k), "sign or zodiac index selected by roundflag", True
    Next k
    SWApiAdd result, "Input ddeg", values(0), "degrees", False
    SWApiAdd result, "Input roundflag", values(1), "split-degree bit mask", False
End Sub

Public Function SW_SWE_VERSION(Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_VERSION = SWApiExecute("swe_version", Array(), options, detail)
End Function

Public Sub SWApiCall104(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_arg1(0 To 255) As Byte
    Dim nativeResult As LongPtr
    Dim k As Long
    nativeResult = Native_swe_version(p_arg1(0))
    result.NativeReturn = nativeResult
    If nativeResult <> VarPtr(p_arg1(0)) Then SWRaise "Unexpected native return pointer."
    result.NativeReturn = SWApiOutputText(p_arg1, "swe_version")
    SWApiCheckReturn result, "value", 0#
    SWApiAdd result, "arg1", SWApiOutputText(p_arg1, "swe_version"), "NUL-terminated string", True
End Sub

