Attribute VB_Name = "SWApiEvents"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_HELIO_CROSS(ByVal v_ipl As Variant, ByVal v_x2cross As Variant, ByVal v_jd_et As Variant, ByVal v_iflag As Variant, ByVal v_dir As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HELIO_CROSS = SWApiExecute("swe_helio_cross", Array(v_ipl, v_x2cross, v_jd_et, v_iflag, v_dir), options, detail)
End Function

Public Sub SWApiCall46(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_ipl As Long
    Dim p_x2cross As Double
    Dim p_jd_et As Double
    Dim p_iflag As Long
    Dim p_dir As Long
    Dim p_jd_cross(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_ipl = SWApiInteger(values(0))
    p_x2cross = SWApiNumber(values(1))
    p_jd_et = SWApiNumber(values(2))
    p_iflag = SWApiInteger(values(3))
    p_dir = SWApiInteger(values(4))
    nativeResult = Native_swe_helio_cross(p_ipl, p_x2cross, p_jd_et, p_iflag, p_dir, p_jd_cross(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", p_jd_et
    For k = 0 To 1 - 1
        SWApiAdd result, "jd_cross[" & CStr(k) & "]", p_jd_cross(k), "Julian day TT or explicitly named input time scale", True
    Next k
    SWApiAdd result, "Input ipl", values(0), "Swiss body ID", False
    SWApiAdd result, "Input x2cross", values(1), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_et", values(2), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input iflag", values(3), "Swiss flag bit mask", False
    SWApiAdd result, "Input dir", values(4), "positive forward or negative backward", False
End Sub

Public Function SW_SWE_HELIO_CROSS_UT(ByVal v_ipl As Variant, ByVal v_x2cross As Variant, ByVal v_jd_ut As Variant, ByVal v_iflag As Variant, ByVal v_dir As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HELIO_CROSS_UT = SWApiExecute("swe_helio_cross_ut", Array(v_ipl, v_x2cross, v_jd_ut, v_iflag, v_dir), options, detail)
End Function

Public Sub SWApiCall47(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_ipl As Long
    Dim p_x2cross As Double
    Dim p_jd_ut As Double
    Dim p_iflag As Long
    Dim p_dir As Long
    Dim p_jd_cross(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_ipl = SWApiInteger(values(0))
    p_x2cross = SWApiNumber(values(1))
    p_jd_ut = SWApiNumber(values(2))
    p_iflag = SWApiInteger(values(3))
    p_dir = SWApiInteger(values(4))
    nativeResult = Native_swe_helio_cross_ut(p_ipl, p_x2cross, p_jd_ut, p_iflag, p_dir, p_jd_cross(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", p_jd_ut
    For k = 0 To 1 - 1
        SWApiAdd result, "jd_cross[" & CStr(k) & "]", p_jd_cross(k), "Julian day UT1", True
    Next k
    SWApiAdd result, "Input ipl", values(0), "Swiss body ID", False
    SWApiAdd result, "Input x2cross", values(1), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_ut", values(2), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(3), "Swiss flag bit mask", False
    SWApiAdd result, "Input dir", values(4), "positive forward or negative backward", False
End Sub

Public Function SW_SWE_LUN_ECLIPSE_HOW(ByVal v_tjd_ut As Variant, ByVal v_ifl As Variant, ByVal v_geopos As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_ECLIPSE_HOW = SWApiExecute("swe_lun_eclipse_how", Array(v_tjd_ut, v_ifl, v_geopos), options, detail)
End Function

Public Sub SWApiCall60(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ifl As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_lun_eclipse_how(p_tjd_ut, p_ifl, p_geopos(0), p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("umbral magnitude", "penumbral magnitude", "reserved", "reserved", "Moon azimuth degrees", "true altitude degrees", "apparent altitude degrees", "opposition distance degrees", "eclipse magnitude", "Saros series", "Saros member", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
End Sub

Public Function SW_SWE_LUN_ECLIPSE_WHEN(ByVal v_tjd_start As Variant, ByVal v_ifl As Variant, ByVal v_ifltype As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_ECLIPSE_WHEN = SWApiExecute("swe_lun_eclipse_when", Array(v_tjd_start, v_ifl, v_ifltype, v_backward), options, detail)
End Function

Public Sub SWApiCall61(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ifl As Long
    Dim p_ifltype As Long
    Dim p_tret(0 To 9) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    p_ifltype = SWApiInteger(values(2))
    p_backward = SWApiInteger(values(3))
    nativeResult = Native_swe_lun_eclipse_when(p_tjd_start, p_ifl, p_ifltype, p_tret(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "reserved", "partial begins JD UT1", "partial ends JD UT1", "total begins JD UT1", "total ends JD UT1", "penumbral begins JD UT1", "penumbral ends JD UT1", "moonrise JD UT1 (local only)", "moonset JD UT1 (local only)")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    SWApiAdd result, "Input ifltype", values(2), "event type bit mask", False
    SWApiAdd result, "Input backward", values(3), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_LUN_ECLIPSE_WHEN_LOC(ByVal v_tjd_start As Variant, ByVal v_ifl As Variant, ByVal v_geopos As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_ECLIPSE_WHEN_LOC = SWApiExecute("swe_lun_eclipse_when_loc", Array(v_tjd_start, v_ifl, v_geopos, v_backward), options, detail)
End Function

Public Sub SWApiCall62(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ifl As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_tret(0 To 9) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    p_backward = SWApiInteger(values(3))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_lun_eclipse_when_loc(p_tjd_start, p_ifl, p_geopos(0), p_tret(0), p_attr(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "reserved", "partial begins JD UT1", "partial ends JD UT1", "total begins JD UT1", "total ends JD UT1", "penumbral begins JD UT1", "penumbral ends JD UT1", "moonrise JD UT1 (local only)", "moonset JD UT1 (local only)")(k)), True
    Next k
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("umbral magnitude", "penumbral magnitude", "reserved", "reserved", "Moon azimuth degrees", "true altitude degrees", "apparent altitude degrees", "opposition distance degrees", "eclipse magnitude", "Saros series", "Saros member", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input backward", values(3), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_LUN_OCCULT_WHEN_GLOB(ByVal v_tjd_start As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_ifl As Variant, ByVal v_ifltype As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_OCCULT_WHEN_GLOB = SWApiExecute("swe_lun_occult_when_glob", Array(v_tjd_start, v_ipl, v_starname, v_ifl, v_ifltype, v_backward), options, detail)
End Function

Public Sub SWApiCall63(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_ifl As Long
    Dim p_ifltype As Long
    Dim p_tret(0 To 9) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_ifl = SWApiInteger(values(3))
    p_ifltype = SWApiInteger(values(4))
    p_backward = SWApiInteger(values(5))
    nativeResult = Native_swe_lun_occult_when_glob(p_tjd_start, p_ipl, p_starname(0), p_ifl, p_ifltype, p_tret(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "local apparent noon JD UT1", "eclipse begins JD UT1", "eclipse ends JD UT1", "totality begins JD UT1", "totality ends JD UT1", "centre line begins JD UT1", "centre line ends JD UT1", "reserved unimplemented", "reserved unimplemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input ifl", values(3), "ephemeris flag bit mask", False
    SWApiAdd result, "Input ifltype", values(4), "event type bit mask", False
    SWApiAdd result, "Input backward", values(5), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_LUN_OCCULT_WHEN_LOC(ByVal v_tjd_start As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_ifl As Variant, ByVal v_geopos As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_OCCULT_WHEN_LOC = SWApiExecute("swe_lun_occult_when_loc", Array(v_tjd_start, v_ipl, v_starname, v_ifl, v_geopos, v_backward), options, detail)
End Function

Public Sub SWApiCall64(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_ifl As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_tret(0 To 9) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_ifl = SWApiInteger(values(3))
    SWApiPutVector p_geopos, values(4), 3
    p_backward = SWApiInteger(values(5))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_lun_occult_when_loc(p_tjd_start, p_ipl, p_starname(0), p_ifl, p_geopos(0), p_tret(0), p_attr(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "first contact JD UT1", "second contact JD UT1", "third contact JD UT1", "fourth contact JD UT1", "sunrise JD UT1", "sunset JD UT1", "reserved", "reserved", "reserved")(k)), True
    Next k
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("diameter fraction covered", "Moon/object diameter ratio", "disc obscuration fraction", "core shadow diameter km", "azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees", "Moon/object separation degrees", "NASA magnitude", "Saros series (-99999999 unavailable)", "Saros member (-99999999 unavailable)", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input ifl", values(3), "ephemeris flag bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input backward", values(5), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_LUN_OCCULT_WHERE(ByVal v_tjd As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_ifl As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_LUN_OCCULT_WHERE = SWApiExecute("swe_lun_occult_where", Array(v_tjd, v_ipl, v_starname, v_ifl), options, detail)
End Function

Public Sub SWApiCall65(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_ifl As Long
    Dim p_geopos(0 To 9) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_ifl = SWApiInteger(values(3))
    nativeResult = Native_swe_lun_occult_where(p_tjd, p_ipl, p_starname(0), p_ifl, p_geopos(0), p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 2 - 1
        SWApiAdd result, "geopos[" & CStr(k) & "]", p_geopos(k), CStr(Array("central longitude degrees east", "central latitude degrees north")(k)), True
    Next k
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("diameter fraction covered", "Moon/object diameter ratio", "disc obscuration fraction", "core shadow diameter km", "azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees", "Moon/object separation degrees", "NASA magnitude", "Saros series (-99999999 unavailable)", "Saros member (-99999999 unavailable)", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input ifl", values(3), "ephemeris flag bit mask", False
End Sub

Public Function SW_SWE_MOONCROSS(ByVal v_x2cross As Variant, ByVal v_jd_et As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_MOONCROSS = SWApiExecute("swe_mooncross", Array(v_x2cross, v_jd_et, v_flag), options, detail)
End Function

Public Sub SWApiCall66(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x2cross As Double
    Dim p_jd_et As Double
    Dim p_flag As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_x2cross = SWApiNumber(values(0))
    p_jd_et = SWApiNumber(values(1))
    p_flag = SWApiInteger(values(2))
    nativeResult = Native_swe_mooncross(p_x2cross, p_jd_et, p_flag, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_et
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_mooncross")
    SWApiAdd result, "Input x2cross", values(0), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_et", values(1), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input flag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_MOONCROSS_NODE(ByVal v_jd_et As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_MOONCROSS_NODE = SWApiExecute("swe_mooncross_node", Array(v_jd_et, v_flag), options, detail)
End Function

Public Sub SWApiCall67(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_jd_et As Double
    Dim p_flag As Long
    Dim p_xlon(0 To 0) As Double
    Dim p_xlat(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_jd_et = SWApiNumber(values(0))
    p_flag = SWApiInteger(values(1))
    nativeResult = Native_swe_mooncross_node(p_jd_et, p_flag, p_xlon(0), p_xlat(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_et
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_mooncross_node")
    For k = 0 To 1 - 1
        SWApiAdd result, "xlon[" & CStr(k) & "]", p_xlon(k), "degrees", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "xlat[" & CStr(k) & "]", p_xlat(k), "degrees", True
    Next k
    SWApiAdd result, "Input jd_et", values(0), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input flag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_MOONCROSS_NODE_UT(ByVal v_jd_ut As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_MOONCROSS_NODE_UT = SWApiExecute("swe_mooncross_node_ut", Array(v_jd_ut, v_flag), options, detail)
End Function

Public Sub SWApiCall68(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_jd_ut As Double
    Dim p_flag As Long
    Dim p_xlon(0 To 0) As Double
    Dim p_xlat(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_jd_ut = SWApiNumber(values(0))
    p_flag = SWApiInteger(values(1))
    nativeResult = Native_swe_mooncross_node_ut(p_jd_ut, p_flag, p_xlon(0), p_xlat(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_ut
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_mooncross_node_ut")
    For k = 0 To 1 - 1
        SWApiAdd result, "xlon[" & CStr(k) & "]", p_xlon(k), "degrees", True
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "xlat[" & CStr(k) & "]", p_xlat(k), "degrees", True
    Next k
    SWApiAdd result, "Input jd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input flag", values(1), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_MOONCROSS_UT(ByVal v_x2cross As Variant, ByVal v_jd_ut As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_MOONCROSS_UT = SWApiExecute("swe_mooncross_ut", Array(v_x2cross, v_jd_ut, v_flag), options, detail)
End Function

Public Sub SWApiCall69(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x2cross As Double
    Dim p_jd_ut As Double
    Dim p_flag As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_x2cross = SWApiNumber(values(0))
    p_jd_ut = SWApiNumber(values(1))
    p_flag = SWApiInteger(values(2))
    nativeResult = Native_swe_mooncross_ut(p_x2cross, p_jd_ut, p_flag, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_ut
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_mooncross_ut")
    SWApiAdd result, "Input x2cross", values(0), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_ut", values(1), "Julian day UT1", False
    SWApiAdd result, "Input flag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_RISE_TRANS(ByVal v_tjd_ut As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_epheflag As Variant, ByVal v_rsmi As Variant, ByVal v_geopos As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_RISE_TRANS = SWApiExecute("swe_rise_trans", Array(v_tjd_ut, v_ipl, v_starname, v_epheflag, v_rsmi, v_geopos, v_atpress, v_attemp), options, detail)
End Function

Public Sub SWApiCall80(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_epheflag As Long
    Dim p_rsmi As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_tret(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_epheflag = SWApiInteger(values(3))
    p_rsmi = SWApiInteger(values(4))
    SWApiPutVector p_geopos, values(5), 3
    p_atpress = SWApiNumber(values(6))
    p_attemp = SWApiNumber(values(7))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_rise_trans(p_tjd_ut, p_ipl, p_starname(0), p_epheflag, p_rsmi, p_geopos(0), p_atpress, p_attemp, p_tret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "rise", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), "Julian day UT1; 0 means unavailable contact", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input epheflag", values(3), "ephemeris flag bit mask", False
    SWApiAdd result, "Input rsmi", values(4), "rise/set/transit bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input atpress", values(6), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(7), "degrees Celsius", False
End Sub

Public Function SW_SWE_RISE_TRANS_TRUE_HOR(ByVal v_tjd_ut As Variant, ByVal v_ipl As Variant, ByVal v_starname As Variant, ByVal v_epheflag As Variant, ByVal v_rsmi As Variant, ByVal v_geopos As Variant, ByVal v_atpress As Variant, ByVal v_attemp As Variant, ByVal v_horhgt As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_RISE_TRANS_TRUE_HOR = SWApiExecute("swe_rise_trans_true_hor", Array(v_tjd_ut, v_ipl, v_starname, v_epheflag, v_rsmi, v_geopos, v_atpress, v_attemp, v_horhgt), options, detail)
End Function

Public Sub SWApiCall81(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_ipl As Long
    Dim p_starname(0 To 255) As Byte
    Dim p_epheflag As Long
    Dim p_rsmi As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_atpress As Double
    Dim p_attemp As Double
    Dim p_horhgt As Double
    Dim p_tret(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    p_ipl = SWApiInteger(values(1))
    SWApiPutText p_starname, CStr(values(2))
    p_epheflag = SWApiInteger(values(3))
    p_rsmi = SWApiInteger(values(4))
    SWApiPutVector p_geopos, values(5), 3
    p_atpress = SWApiNumber(values(6))
    p_attemp = SWApiNumber(values(7))
    p_horhgt = SWApiNumber(values(8))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_rise_trans_true_hor(p_tjd_ut, p_ipl, p_starname(0), p_epheflag, p_rsmi, p_geopos(0), p_atpress, p_attemp, p_horhgt, p_tret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "rise", 0#
    For k = 0 To 1 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), "Julian day UT1; 0 means unavailable contact", True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ipl", values(1), "Swiss body ID", False
    SWApiAdd result, "Input starname", values(2), "star name, or empty to use ipl", False
    SWApiAdd result, "Input epheflag", values(3), "ephemeris flag bit mask", False
    SWApiAdd result, "Input rsmi", values(4), "rise/set/transit bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input atpress", values(6), "hPa (0 estimates pressure)", False
    SWApiAdd result, "Input attemp", values(7), "degrees Celsius", False
    SWApiAdd result, "Input horhgt", values(8), "degrees", False
End Sub

Public Function SW_SWE_SOL_ECLIPSE_HOW(ByVal v_tjd As Variant, ByVal v_ifl As Variant, ByVal v_geopos As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOL_ECLIPSE_HOW = SWApiExecute("swe_sol_eclipse_how", Array(v_tjd, v_ifl, v_geopos), options, detail)
End Function

Public Sub SWApiCall93(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ifl As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_sol_eclipse_how(p_tjd, p_ifl, p_geopos(0), p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("diameter fraction covered", "Moon/object diameter ratio", "disc obscuration fraction", "core shadow diameter km", "azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees", "Moon/object separation degrees", "NASA magnitude", "Saros series (-99999999 unavailable)", "Saros member (-99999999 unavailable)", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
End Sub

Public Function SW_SWE_SOL_ECLIPSE_WHEN_GLOB(ByVal v_tjd_start As Variant, ByVal v_ifl As Variant, ByVal v_ifltype As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOL_ECLIPSE_WHEN_GLOB = SWApiExecute("swe_sol_eclipse_when_glob", Array(v_tjd_start, v_ifl, v_ifltype, v_backward), options, detail)
End Function

Public Sub SWApiCall94(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ifl As Long
    Dim p_ifltype As Long
    Dim p_tret(0 To 9) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    p_ifltype = SWApiInteger(values(2))
    p_backward = SWApiInteger(values(3))
    nativeResult = Native_swe_sol_eclipse_when_glob(p_tjd_start, p_ifl, p_ifltype, p_tret(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "local apparent noon JD UT1", "eclipse begins JD UT1", "eclipse ends JD UT1", "totality begins JD UT1", "totality ends JD UT1", "centre line begins JD UT1", "centre line ends JD UT1", "reserved unimplemented", "reserved unimplemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    SWApiAdd result, "Input ifltype", values(2), "event type bit mask", False
    SWApiAdd result, "Input backward", values(3), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_SOL_ECLIPSE_WHEN_LOC(ByVal v_tjd_start As Variant, ByVal v_ifl As Variant, ByVal v_geopos As Variant, ByVal v_backward As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOL_ECLIPSE_WHEN_LOC = SWApiExecute("swe_sol_eclipse_when_loc", Array(v_tjd_start, v_ifl, v_geopos, v_backward), options, detail)
End Function

Public Sub SWApiCall95(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_start As Double
    Dim p_ifl As Long
    Dim p_geopos(0 To 2) As Double
    Dim p_tret(0 To 9) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_backward As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_start = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    SWApiPutVector p_geopos, values(2), 3
    p_backward = SWApiInteger(values(3))
    SWApiValidateObserver p_geopos
    nativeResult = Native_swe_sol_eclipse_when_loc(p_tjd_start, p_ifl, p_geopos(0), p_tret(0), p_attr(0), p_backward, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 10 - 1
        SWApiAdd result, "tret[" & CStr(k) & "]", p_tret(k), CStr(Array("maximum JD UT1", "first contact JD UT1", "second contact JD UT1", "third contact JD UT1", "fourth contact JD UT1", "sunrise JD UT1", "sunset JD UT1", "reserved", "reserved", "reserved")(k)), True
    Next k
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("diameter fraction covered", "Moon/object diameter ratio", "disc obscuration fraction", "core shadow diameter km", "azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees", "Moon/object separation degrees", "NASA magnitude", "Saros series (-99999999 unavailable)", "Saros member (-99999999 unavailable)", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd_start", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    SWApiAdd result, "Input backward", values(3), "0 forward, 1 backward; occultation one-try bit 32768", False
End Sub

Public Function SW_SWE_SOL_ECLIPSE_WHERE(ByVal v_tjd As Variant, ByVal v_ifl As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOL_ECLIPSE_WHERE = SWApiExecute("swe_sol_eclipse_where", Array(v_tjd, v_ifl), options, detail)
End Function

Public Sub SWApiCall96(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd As Double
    Dim p_ifl As Long
    Dim p_geopos(0 To 9) As Double
    Dim p_attr(0 To 19) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd = SWApiNumber(values(0))
    p_ifl = SWApiInteger(values(1))
    nativeResult = Native_swe_sol_eclipse_where(p_tjd, p_ifl, p_geopos(0), p_attr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "event", 0#
    For k = 0 To 2 - 1
        SWApiAdd result, "geopos[" & CStr(k) & "]", p_geopos(k), CStr(Array("central longitude degrees east", "central latitude degrees north")(k)), True
    Next k
    For k = 0 To 20 - 1
        SWApiAdd result, "attr[" & CStr(k) & "]", p_attr(k), CStr(Array("diameter fraction covered", "Moon/object diameter ratio", "disc obscuration fraction", "core shadow diameter km", "azimuth south through west degrees", "true altitude degrees", "apparent altitude degrees", "Moon/object separation degrees", "NASA magnitude", "Saros series (-99999999 unavailable)", "Saros member (-99999999 unavailable)", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented", "reserved / not implemented")(k)), True
    Next k
    SWApiAdd result, "Input tjd", values(0), "Julian day UT1", False
    SWApiAdd result, "Input ifl", values(1), "ephemeris flag bit mask", False
End Sub

Public Function SW_SWE_SOLCROSS(ByVal v_x2cross As Variant, ByVal v_jd_et As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOLCROSS = SWApiExecute("swe_solcross", Array(v_x2cross, v_jd_et, v_flag), options, detail)
End Function

Public Sub SWApiCall97(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x2cross As Double
    Dim p_jd_et As Double
    Dim p_flag As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_x2cross = SWApiNumber(values(0))
    p_jd_et = SWApiNumber(values(1))
    p_flag = SWApiInteger(values(2))
    nativeResult = Native_swe_solcross(p_x2cross, p_jd_et, p_flag, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_et
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_solcross")
    SWApiAdd result, "Input x2cross", values(0), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_et", values(1), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input flag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_SOLCROSS_UT(ByVal v_x2cross As Variant, ByVal v_jd_ut As Variant, ByVal v_flag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_SOLCROSS_UT = SWApiExecute("swe_solcross_ut", Array(v_x2cross, v_jd_ut, v_flag), options, detail)
End Function

Public Sub SWApiCall98(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_x2cross As Double
    Dim p_jd_ut As Double
    Dim p_flag As Long
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Double
    Dim k As Long
    p_x2cross = SWApiNumber(values(0))
    p_jd_ut = SWApiNumber(values(1))
    p_flag = SWApiInteger(values(2))
    nativeResult = Native_swe_solcross_ut(p_x2cross, p_jd_ut, p_flag, p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "crossing", p_jd_ut
    SWApiAdd result, "Result", result.NativeReturn, SWApiReturnUnit("swe_solcross_ut")
    SWApiAdd result, "Input x2cross", values(0), "target ecliptic longitude, degrees", False
    SWApiAdd result, "Input jd_ut", values(1), "Julian day UT1", False
    SWApiAdd result, "Input flag", values(2), "Swiss flag bit mask", False
End Sub

