Attribute VB_Name = "SWApiHeliacal"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_HELIACAL_ANGLE(ByVal v_tjdut As Variant, ByVal v_dgeo As Variant, ByVal v_datm As Variant, ByVal v_dobs As Variant, ByVal v_helflag As Variant, ByVal v_mag As Variant, ByVal v_azi_obj As Variant, ByVal v_azi_sun As Variant, ByVal v_azi_moon As Variant, ByVal v_alt_moon As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HELIACAL_ANGLE = SWApiExecute("swe_heliacal_angle", Array(v_tjdut, v_dgeo, v_datm, v_dobs, v_helflag, v_mag, v_azi_obj, v_azi_sun, v_azi_moon, v_alt_moon), options, detail)
End Function

Public Sub SWApiCall43(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjdut As Double
    Dim p_dgeo(0 To 2) As Double
    Dim p_datm(0 To 3) As Double
    Dim p_dobs(0 To 5) As Double
    Dim p_helflag As Long
    Dim p_mag As Double
    Dim p_azi_obj As Double
    Dim p_azi_sun As Double
    Dim p_azi_moon As Double
    Dim p_alt_moon As Double
    Dim p_dret(0 To 2) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjdut = SWApiNumber(values(0))
    SWApiPutVector p_dgeo, values(1), 3
    SWApiPutVector p_datm, values(2), 4
    SWApiPutVector p_dobs, values(3), 6
    p_helflag = SWApiInteger(values(4))
    p_mag = SWApiNumber(values(5))
    p_azi_obj = SWApiNumber(values(6))
    p_azi_sun = SWApiNumber(values(7))
    p_azi_moon = SWApiNumber(values(8))
    p_alt_moon = SWApiNumber(values(9))
    SWApiValidateObserver p_dgeo
    SWApiValidateHeliacal p_datm, p_dobs
    nativeResult = Native_swe_heliacal_angle(p_tjdut, p_dgeo(0), p_datm(0), p_dobs(0), p_helflag, p_mag, p_azi_obj, p_azi_sun, p_azi_moon, p_alt_moon, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 4 - 1
        SWApiAdd result, "datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    For k = 0 To 3 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("optimum object altitude degrees", "minimum arcus visionis degrees", "Sun altitude degrees")(k)), True
    Next k
    SWApiAdd result, "Input tjdut", values(0), "Julian day UT1", False
    For k = 0 To 2
        SWApiAdd result, "Effective input dgeo[" & CStr(k) & "]", p_dgeo(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 3
        SWApiAdd result, "Effective input datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    SWApiAdd result, "Input helflag", values(4), "heliacal flag bit mask", False
    SWApiAdd result, "Input mag", values(5), "astronomical magnitude", False
    SWApiAdd result, "Input azi_obj", values(6), "azimuth degrees", False
    SWApiAdd result, "Input azi_sun", values(7), "azimuth degrees", False
    SWApiAdd result, "Input azi_moon", values(8), "azimuth degrees", False
    SWApiAdd result, "Input alt_moon", values(9), "altitude degrees", False
End Sub

Public Function SW_SWE_HELIACAL_PHENO_UT(ByVal v_tjd_ut As Variant, ByVal v_geopos As Variant, ByVal v_datm As Variant, ByVal v_dobs As Variant, ByVal v_ObjectName As Variant, ByVal v_TypeEvent As Variant, ByVal v_helflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HELIACAL_PHENO_UT = SWApiExecute("swe_heliacal_pheno_ut", Array(v_tjd_ut, v_geopos, v_datm, v_dobs, v_ObjectName, v_TypeEvent, v_helflag), options, detail)
End Function

Public Sub SWApiCall44(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjd_ut As Double
    Dim p_geopos(0 To 2) As Double
    Dim p_datm(0 To 3) As Double
    Dim p_dobs(0 To 5) As Double
    Dim p_ObjectName(0 To 255) As Byte
    Dim p_TypeEvent As Long
    Dim p_helflag As Long
    Dim p_darr(0 To 49) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjd_ut = SWApiNumber(values(0))
    SWApiPutVector p_geopos, values(1), 3
    SWApiPutVector p_datm, values(2), 4
    SWApiPutVector p_dobs, values(3), 6
    SWApiPutText p_ObjectName, CStr(values(4))
    p_TypeEvent = SWApiInteger(values(5))
    p_helflag = SWApiInteger(values(6))
    SWApiValidateObserver p_geopos
    SWApiValidateHeliacal p_datm, p_dobs
    If p_TypeEvent < 1 Or p_TypeEvent > 6 Then SWRaise "Event type must be 1..6."
    nativeResult = Native_swe_heliacal_pheno_ut(p_tjd_ut, p_geopos(0), p_datm(0), p_dobs(0), p_ObjectName(0), p_TypeEvent, p_helflag, p_darr(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 4 - 1
        SWApiAdd result, "datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    For k = 0 To 28 - 1
        SWApiAdd result, "darr[" & CStr(k) & "]", p_darr(k), CStr(Array("object true altitude degrees", "object apparent altitude degrees", "geocentric altitude degrees", "object azimuth degrees", "Sun altitude degrees", "Sun azimuth degrees", "topocentric arcus visionis degrees", "geocentric arcus visionis degrees", "azimuth difference degrees", "longitude difference degrees", "extinction coefficient", "minimum arcus visionis degrees", "first visibility JD UT1", "optimum visibility JD UT1", "last visibility JD UT1", "Yallop best time JD UT1", "crescent width degrees", "Yallop q", "Yallop criterion", "parallax degrees", "magnitude", "object rise/set JD UT1", "Sun rise/set JD UT1", "lag days", "visibility duration days", "crescent length degrees", "elongation degrees", "illuminated percent")(k)), True
    Next k
    SWApiAdd result, "Input tjd_ut", values(0), "Julian day UT1", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 3
        SWApiAdd result, "Effective input datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    SWApiAdd result, "Input ObjectName", values(4), "planet or fixed-star name", False
    SWApiAdd result, "Input TypeEvent", values(5), "heliacal event type 1..6", False
    SWApiAdd result, "Input helflag", values(6), "heliacal flag bit mask", False
End Sub

Public Function SW_SWE_HELIACAL_UT(ByVal v_tjdstart_ut As Variant, ByVal v_geopos As Variant, ByVal v_datm As Variant, ByVal v_dobs As Variant, ByVal v_ObjectName As Variant, ByVal v_TypeEvent As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_HELIACAL_UT = SWApiExecute("swe_heliacal_ut", Array(v_tjdstart_ut, v_geopos, v_datm, v_dobs, v_ObjectName, v_TypeEvent, v_iflag), options, detail)
End Function

Public Sub SWApiCall45(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjdstart_ut As Double
    Dim p_geopos(0 To 2) As Double
    Dim p_datm(0 To 3) As Double
    Dim p_dobs(0 To 5) As Double
    Dim p_ObjectName(0 To 255) As Byte
    Dim p_TypeEvent As Long
    Dim p_iflag As Long
    Dim p_dret(0 To 9) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjdstart_ut = SWApiNumber(values(0))
    SWApiPutVector p_geopos, values(1), 3
    SWApiPutVector p_datm, values(2), 4
    SWApiPutVector p_dobs, values(3), 6
    SWApiPutText p_ObjectName, CStr(values(4))
    p_TypeEvent = SWApiInteger(values(5))
    p_iflag = SWApiInteger(values(6))
    SWApiValidateObserver p_geopos
    SWApiValidateHeliacal p_datm, p_dobs
    If p_TypeEvent < 1 Or p_TypeEvent > 6 Then SWRaise "Event type must be 1..6."
    nativeResult = Native_swe_heliacal_ut(p_tjdstart_ut, p_geopos(0), p_datm(0), p_dobs(0), p_ObjectName(0), p_TypeEvent, p_iflag, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 4 - 1
        SWApiAdd result, "datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    For k = 0 To 3 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("first visibility JD UT1", "optimum visibility JD UT1", "last visibility JD UT1")(k)), True
    Next k
    SWApiAdd result, "Input tjdstart_ut", values(0), "Julian day UT1", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 3
        SWApiAdd result, "Effective input datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    SWApiAdd result, "Input ObjectName", values(4), "planet or fixed-star name", False
    SWApiAdd result, "Input TypeEvent", values(5), "heliacal event type 1..6", False
    SWApiAdd result, "Input iflag", values(6), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_TOPO_ARCUS_VISIONIS(ByVal v_tjdut As Variant, ByVal v_dgeo As Variant, ByVal v_datm As Variant, ByVal v_dobs As Variant, ByVal v_helflag As Variant, ByVal v_mag As Variant, ByVal v_azi_obj As Variant, ByVal v_alt_obj As Variant, ByVal v_azi_sun As Variant, ByVal v_azi_moon As Variant, ByVal v_alt_moon As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_TOPO_ARCUS_VISIONIS = SWApiExecute("swe_topo_arcus_visionis", Array(v_tjdut, v_dgeo, v_datm, v_dobs, v_helflag, v_mag, v_azi_obj, v_alt_obj, v_azi_sun, v_azi_moon, v_alt_moon), options, detail)
End Function

Public Sub SWApiCall101(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjdut As Double
    Dim p_dgeo(0 To 2) As Double
    Dim p_datm(0 To 3) As Double
    Dim p_dobs(0 To 5) As Double
    Dim p_helflag As Long
    Dim p_mag As Double
    Dim p_azi_obj As Double
    Dim p_alt_obj As Double
    Dim p_azi_sun As Double
    Dim p_azi_moon As Double
    Dim p_alt_moon As Double
    Dim p_dret(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjdut = SWApiNumber(values(0))
    SWApiPutVector p_dgeo, values(1), 3
    SWApiPutVector p_datm, values(2), 4
    SWApiPutVector p_dobs, values(3), 6
    p_helflag = SWApiInteger(values(4))
    p_mag = SWApiNumber(values(5))
    p_azi_obj = SWApiNumber(values(6))
    p_alt_obj = SWApiNumber(values(7))
    p_azi_sun = SWApiNumber(values(8))
    p_azi_moon = SWApiNumber(values(9))
    p_alt_moon = SWApiNumber(values(10))
    SWApiValidateObserver p_dgeo
    SWApiValidateHeliacal p_datm, p_dobs
    nativeResult = Native_swe_topo_arcus_visionis(p_tjdut, p_dgeo(0), p_datm(0), p_dobs(0), p_helflag, p_mag, p_azi_obj, p_alt_obj, p_azi_sun, p_azi_moon, p_alt_moon, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    For k = 0 To 4 - 1
        SWApiAdd result, "datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    For k = 0 To 1 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), "arcus visionis degrees", True
    Next k
    SWApiAdd result, "Input tjdut", values(0), "Julian day UT1", False
    For k = 0 To 2
        SWApiAdd result, "Effective input dgeo[" & CStr(k) & "]", p_dgeo(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 3
        SWApiAdd result, "Effective input datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    SWApiAdd result, "Input helflag", values(4), "heliacal flag bit mask", False
    SWApiAdd result, "Input mag", values(5), "astronomical magnitude", False
    SWApiAdd result, "Input azi_obj", values(6), "azimuth degrees", False
    SWApiAdd result, "Input alt_obj", values(7), "altitude degrees", False
    SWApiAdd result, "Input azi_sun", values(8), "azimuth degrees", False
    SWApiAdd result, "Input azi_moon", values(9), "azimuth degrees", False
    SWApiAdd result, "Input alt_moon", values(10), "altitude degrees", False
End Sub

Public Function SW_SWE_VIS_LIMIT_MAG(ByVal v_tjdut As Variant, ByVal v_geopos As Variant, ByVal v_datm As Variant, ByVal v_dobs As Variant, ByVal v_ObjectName As Variant, ByVal v_helflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_VIS_LIMIT_MAG = SWApiExecute("swe_vis_limit_mag", Array(v_tjdut, v_geopos, v_datm, v_dobs, v_ObjectName, v_helflag), options, detail)
End Function

Public Sub SWApiCall105(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_tjdut As Double
    Dim p_geopos(0 To 2) As Double
    Dim p_datm(0 To 3) As Double
    Dim p_dobs(0 To 5) As Double
    Dim p_ObjectName(0 To 255) As Byte
    Dim p_helflag As Long
    Dim p_dret(0 To 9) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    p_tjdut = SWApiNumber(values(0))
    SWApiPutVector p_geopos, values(1), 3
    SWApiPutVector p_datm, values(2), 4
    SWApiPutVector p_dobs, values(3), 6
    SWApiPutText p_ObjectName, CStr(values(4))
    p_helflag = SWApiInteger(values(5))
    SWApiValidateObserver p_geopos
    SWApiValidateHeliacal p_datm, p_dobs
    nativeResult = Native_swe_vis_limit_mag(p_tjdut, p_geopos(0), p_datm(0), p_dobs(0), p_ObjectName(0), p_helflag, p_dret(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "visibility", 0#
    For k = 0 To 4 - 1
        SWApiAdd result, "datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 6 - 1
        SWApiAdd result, "dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    For k = 0 To 8 - 1
        SWApiAdd result, "dret[" & CStr(k) & "]", p_dret(k), CStr(Array("limiting magnitude", "object altitude degrees", "object azimuth degrees", "Sun altitude degrees", "Sun azimuth degrees", "Moon altitude degrees", "Moon azimuth degrees", "object magnitude")(k)), True
    Next k
    SWApiAdd result, "Input tjdut", values(0), "Julian day UT1", False
    For k = 0 To 2
        SWApiAdd result, "Effective input geopos[" & CStr(k) & "]", p_geopos(k), "degrees east; degrees north; metres above sea level", False
    Next k
    For k = 0 To 3
        SWApiAdd result, "Effective input datm[" & CStr(k) & "]", p_datm(k), "hPa; Celsius; relative humidity percent; visibility km or extinction coefficient", False
    Next k
    For k = 0 To 5
        SWApiAdd result, "Effective input dobs[" & CStr(k) & "]", p_dobs(k), "age years; Snellen ratio; binocular flag; magnification; aperture mm; transmission fraction", False
    Next k
    SWApiAdd result, "Input ObjectName", values(4), "planet or fixed-star name", False
    SWApiAdd result, "Input helflag", values(5), "heliacal flag bit mask", False
End Sub

