Attribute VB_Name = "SWApiStars"
Option Explicit
' Generated by tools/generate_api.py. SPDX-License-Identifier: AGPL-3.0-or-later

Public Function SW_SWE_FIXSTAR(ByVal v_star As Variant, ByVal v_tjd As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR = SWApiExecute("swe_fixstar", Array(v_star, v_tjd, v_iflag), options, detail)
End Function

Public Sub SWApiCall25(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_tjd As Double
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    p_tjd = SWApiNumber(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_fixstar(p_star(0), p_tjd, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
    SWApiAdd result, "Input tjd", values(1), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_FIXSTAR2(ByVal v_star As Variant, ByVal v_tjd As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR2 = SWApiExecute("swe_fixstar2", Array(v_star, v_tjd, v_iflag), options, detail)
End Function

Public Sub SWApiCall26(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_tjd As Double
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    p_tjd = SWApiNumber(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_fixstar2(p_star(0), p_tjd, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar2"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
    SWApiAdd result, "Input tjd", values(1), "Julian day TT or explicitly named input time scale", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_FIXSTAR2_MAG(ByVal v_star As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR2_MAG = SWApiExecute("swe_fixstar2_mag", Array(v_star), options, detail)
End Function

Public Sub SWApiCall27(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_mag(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    nativeResult = Native_swe_fixstar2_mag(p_star(0), p_mag(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar2_mag"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 1 - 1
        SWApiAdd result, "mag[" & CStr(k) & "]", p_mag(k), "astronomical magnitude", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
End Sub

Public Function SW_SWE_FIXSTAR2_UT(ByVal v_star As Variant, ByVal v_tjd_ut As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR2_UT = SWApiExecute("swe_fixstar2_ut", Array(v_star, v_tjd_ut, v_iflag), options, detail)
End Function

Public Sub SWApiCall28(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_tjd_ut As Double
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    p_tjd_ut = SWApiNumber(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_fixstar2_ut(p_star(0), p_tjd_ut, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar2_ut"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
    SWApiAdd result, "Input tjd_ut", values(1), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

Public Function SW_SWE_FIXSTAR_MAG(ByVal v_star As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR_MAG = SWApiExecute("swe_fixstar_mag", Array(v_star), options, detail)
End Function

Public Sub SWApiCall29(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_mag(0 To 0) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    nativeResult = Native_swe_fixstar_mag(p_star(0), p_mag(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "status", 0#
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar_mag"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 1 - 1
        SWApiAdd result, "mag[" & CStr(k) & "]", p_mag(k), "astronomical magnitude", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
End Sub

Public Function SW_SWE_FIXSTAR_UT(ByVal v_star As Variant, ByVal v_tjd_ut As Variant, ByVal v_iflag As Variant, Optional ByVal options As Variant, Optional ByVal detail As Boolean = False) As Variant
    If IsMissing(options) Then options = Empty
    SW_SWE_FIXSTAR_UT = SWApiExecute("swe_fixstar_ut", Array(v_star, v_tjd_ut, v_iflag), options, detail)
End Function

Public Sub SWApiCall30(ByRef result As SWApiResult, ByVal values As Variant)
    Dim p_star(0 To 255) As Byte
    Dim p_tjd_ut As Double
    Dim p_iflag As Long
    Dim p_xx(0 To 5) As Double
    Dim p_serr(0 To 255) As Byte
    Dim nativeResult As Long
    Dim k As Long
    SWApiPutText p_star, CStr(values(0))
    p_tjd_ut = SWApiNumber(values(1))
    p_iflag = SWApiInteger(values(2))
    nativeResult = Native_swe_fixstar_ut(p_star(0), p_tjd_ut, p_iflag, p_xx(0), p_serr(0))
    result.NativeReturn = nativeResult
    result.Warning = SWBufferText(p_serr)
    SWApiCheckReturn result, "flags", 0#
    SWApiCheckFlags result, p_iflag
    SWApiAdd result, "star", SWApiOutputText(p_star, "swe_fixstar_ut"), "star name or catalog index; canonical name is returned", False
    For k = 0 To 6 - 1
        SWApiAdd result, "xx[" & CStr(k) & "]", p_xx(k), "coordinate units selected by flags: degrees/radians or AU, followed by per-day speeds", True
    Next k
    SWApiAdd result, "Input star", values(0), "star name or catalog index; canonical name is returned", False
    SWApiAdd result, "Input tjd_ut", values(1), "Julian day UT1", False
    SWApiAdd result, "Input iflag", values(2), "Swiss flag bit mask", False
End Sub

