Attribute VB_Name = "SWNative"
Option Explicit
Option Private Module

' Generated by tools/generate_bindings.py; do not hand-edit this module.
' Upstream v2.10.3bfinal, commit f4dcd18e8005dde95fd8a8d2312ed12f9accd1b0.
' Retain vendor/swisseph/LICENSE and the notices in the pinned headers.
' Raw Windows x64 ABI only: declarations do not imply tested wrappers.
' Pass first elements of correctly sized numeric/Byte buffers ByRef.
' C strings require a NUL terminator; LongPtr returns are pointers, not VBA Strings.
' Long represents 32-bit C integers/AS_BOOL, not pointer-sized integers.
' Windows x64 uses the unified Microsoft x64 calling convention.

' void swe_azalt(double tjd_ut, int32 calc_flag, double *geopos, double atpress, double attemp, double *xin, double *xaz);
Public Declare PtrSafe Sub Native_swe_azalt Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_azalt" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_calc_flag As Long, _
        ByRef p_geopos As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByRef p_xin As Double, _
        ByRef p_xaz As Double _
    )

' void swe_azalt_rev(double tjd_ut, int32 calc_flag, double *geopos, double *xin, double *xout);
Public Declare PtrSafe Sub Native_swe_azalt_rev Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_azalt_rev" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_calc_flag As Long, _
        ByRef p_geopos As Double, _
        ByRef p_xin As Double, _
        ByRef p_xout As Double _
    )

' int32 swe_calc(double tjd, int ipl, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_calc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_calc" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_calc_pctr(double tjd, int32 ipl, int32 iplctr, int32 iflag, double *xxret, char *serr);
Public Declare PtrSafe Function Native_swe_calc_pctr Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_calc_pctr" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iplctr As Long, _
        ByVal p_iflag As Long, _
        ByRef p_xxret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_calc_ut(double tjd_ut, int32 ipl, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_calc_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_calc_ut" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' void swe_close(void);
Public Declare PtrSafe Sub Native_swe_close Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_close" _
    ()

' void swe_cotrans(double *xpo, double *xpn, double eps);
Public Declare PtrSafe Sub Native_swe_cotrans Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_cotrans" _
    ( _
        ByRef p_xpo As Double, _
        ByRef p_xpn As Double, _
        ByVal p_eps As Double _
    )

' void swe_cotrans_sp(double *xpo, double *xpn, double eps);
Public Declare PtrSafe Sub Native_swe_cotrans_sp Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_cotrans_sp" _
    ( _
        ByRef p_xpo As Double, _
        ByRef p_xpn As Double, _
        ByVal p_eps As Double _
    )

' char * swe_cs2degstr(CSEC t, char *a);
Public Declare PtrSafe Function Native_swe_cs2degstr Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_cs2degstr" _
    ( _
        ByVal p_t As Long, _
        ByRef p_a As Byte _
    ) As LongPtr

' char * swe_cs2lonlatstr(CSEC t, char pchar, char mchar, char *s);
Public Declare PtrSafe Function Native_swe_cs2lonlatstr Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_cs2lonlatstr" _
    ( _
        ByVal p_t As Long, _
        ByVal p_pchar As Byte, _
        ByVal p_mchar As Byte, _
        ByRef p_s As Byte _
    ) As LongPtr

' char * swe_cs2timestr(CSEC t, int sep, AS_BOOL suppressZero, char *a);
Public Declare PtrSafe Function Native_swe_cs2timestr Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_cs2timestr" _
    ( _
        ByVal p_t As Long, _
        ByVal p_sep As Long, _
        ByVal p_suppressZero As Long, _
        ByRef p_a As Byte _
    ) As LongPtr

' centisec swe_csnorm(centisec p);
Public Declare PtrSafe Function Native_swe_csnorm Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_csnorm" _
    ( _
        ByVal p_p As Long _
    ) As Long

' centisec swe_csroundsec(centisec x);
Public Declare PtrSafe Function Native_swe_csroundsec Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_csroundsec" _
    ( _
        ByVal p_x As Long _
    ) As Long

' int32 swe_d2l(double x);
Public Declare PtrSafe Function Native_swe_d2l Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_d2l" _
    ( _
        ByVal p_x As Double _
    ) As Long

' int swe_date_conversion(int y, int m, int d, double utime, char c, double *tjd);
Public Declare PtrSafe Function Native_swe_date_conversion Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_date_conversion" _
    ( _
        ByVal p_y As Long, _
        ByVal p_m As Long, _
        ByVal p_d As Long, _
        ByVal p_utime As Double, _
        ByVal p_c As Byte, _
        ByRef p_tjd As Double _
    ) As Long

' int swe_day_of_week(double jd);
Public Declare PtrSafe Function Native_swe_day_of_week Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_day_of_week" _
    ( _
        ByVal p_jd As Double _
    ) As Long

' double swe_deg_midp(double x1, double x0);
Public Declare PtrSafe Function Native_swe_deg_midp Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_deg_midp" _
    ( _
        ByVal p_x1 As Double, _
        ByVal p_x0 As Double _
    ) As Double

' double swe_degnorm(double x);
Public Declare PtrSafe Function Native_swe_degnorm Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_degnorm" _
    ( _
        ByVal p_x As Double _
    ) As Double

' double swe_deltat(double tjd);
Public Declare PtrSafe Function Native_swe_deltat Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_deltat" _
    ( _
        ByVal p_tjd As Double _
    ) As Double

' double swe_deltat_ex(double tjd, int32 iflag, char *serr);
Public Declare PtrSafe Function Native_swe_deltat_ex Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_deltat_ex" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_iflag As Long, _
        ByRef p_serr As Byte _
    ) As Double

' centisec swe_difcs2n(centisec p1, centisec p2);
Public Declare PtrSafe Function Native_swe_difcs2n Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_difcs2n" _
    ( _
        ByVal p_p1 As Long, _
        ByVal p_p2 As Long _
    ) As Long

' centisec swe_difcsn(centisec p1, centisec p2);
Public Declare PtrSafe Function Native_swe_difcsn Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_difcsn" _
    ( _
        ByVal p_p1 As Long, _
        ByVal p_p2 As Long _
    ) As Long

' double swe_difdeg2n(double p1, double p2);
Public Declare PtrSafe Function Native_swe_difdeg2n Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_difdeg2n" _
    ( _
        ByVal p_p1 As Double, _
        ByVal p_p2 As Double _
    ) As Double

' double swe_difdegn(double p1, double p2);
Public Declare PtrSafe Function Native_swe_difdegn Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_difdegn" _
    ( _
        ByVal p_p1 As Double, _
        ByVal p_p2 As Double _
    ) As Double

' double swe_difrad2n(double p1, double p2);
Public Declare PtrSafe Function Native_swe_difrad2n Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_difrad2n" _
    ( _
        ByVal p_p1 As Double, _
        ByVal p_p2 As Double _
    ) As Double

' int32 swe_fixstar(char *star, double tjd, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar" _
    ( _
        ByRef p_star As Byte, _
        ByVal p_tjd As Double, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_fixstar2(char *star, double tjd, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar2 Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar2" _
    ( _
        ByRef p_star As Byte, _
        ByVal p_tjd As Double, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_fixstar2_mag(char *star, double *mag, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar2_mag Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar2_mag" _
    ( _
        ByRef p_star As Byte, _
        ByRef p_mag As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_fixstar2_ut(char *star, double tjd_ut, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar2_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar2_ut" _
    ( _
        ByRef p_star As Byte, _
        ByVal p_tjd_ut As Double, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_fixstar_mag(char *star, double *mag, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar_mag Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar_mag" _
    ( _
        ByRef p_star As Byte, _
        ByRef p_mag As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_fixstar_ut(char *star, double tjd_ut, int32 iflag, double *xx, char *serr);
Public Declare PtrSafe Function Native_swe_fixstar_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_fixstar_ut" _
    ( _
        ByRef p_star As Byte, _
        ByVal p_tjd_ut As Double, _
        ByVal p_iflag As Long, _
        ByRef p_xx As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_gauquelin_sector(double t_ut, int32 ipl, char *starname, int32 iflag, int32 imeth, double *geopos, double atpress, double attemp, double *dgsect, char *serr);
Public Declare PtrSafe Function Native_swe_gauquelin_sector Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_gauquelin_sector" _
    ( _
        ByVal p_t_ut As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_iflag As Long, _
        ByVal p_imeth As Long, _
        ByRef p_geopos As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByRef p_dgsect As Double, _
        ByRef p_serr As Byte _
    ) As Long

' EXPERIMENTAL / upstream internal: Upstream labels this API 'secret, for Dieter' for model testing.
' void swe_get_astro_models(char *samod, char *sdet, int32 iflag);
Public Declare PtrSafe Sub Native_swe_get_astro_models Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_astro_models" _
    ( _
        ByRef p_samod As Byte, _
        ByRef p_sdet As Byte, _
        ByVal p_iflag As Long _
    )

' double swe_get_ayanamsa(double tjd_et);
Public Declare PtrSafe Function Native_swe_get_ayanamsa Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_ayanamsa" _
    ( _
        ByVal p_tjd_et As Double _
    ) As Double

' int32 swe_get_ayanamsa_ex(double tjd_et, int32 iflag, double *daya, char *serr);
Public Declare PtrSafe Function Native_swe_get_ayanamsa_ex Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_ayanamsa_ex" _
    ( _
        ByVal p_tjd_et As Double, _
        ByVal p_iflag As Long, _
        ByRef p_daya As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_get_ayanamsa_ex_ut(double tjd_ut, int32 iflag, double *daya, char *serr);
Public Declare PtrSafe Function Native_swe_get_ayanamsa_ex_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_ayanamsa_ex_ut" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_iflag As Long, _
        ByRef p_daya As Double, _
        ByRef p_serr As Byte _
    ) As Long

' const char * swe_get_ayanamsa_name(int32 isidmode);
Public Declare PtrSafe Function Native_swe_get_ayanamsa_name Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_ayanamsa_name" _
    ( _
        ByVal p_isidmode As Long _
    ) As LongPtr

' double swe_get_ayanamsa_ut(double tjd_ut);
Public Declare PtrSafe Function Native_swe_get_ayanamsa_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_ayanamsa_ut" _
    ( _
        ByVal p_tjd_ut As Double _
    ) As Double

' const char * swe_get_current_file_data(int ifno, double *tfstart, double *tfend, int *denum);
Public Declare PtrSafe Function Native_swe_get_current_file_data Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_current_file_data" _
    ( _
        ByVal p_ifno As Long, _
        ByRef p_tfstart As Double, _
        ByRef p_tfend As Double, _
        ByRef p_denum As Long _
    ) As LongPtr

' char * swe_get_library_path(char *);
Public Declare PtrSafe Function Native_swe_get_library_path Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_library_path" _
    ( _
        ByRef p_arg1 As Byte _
    ) As LongPtr

' int32 swe_get_orbital_elements(double tjd_et, int32 ipl, int32 iflag, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_get_orbital_elements Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_orbital_elements" _
    ( _
        ByVal p_tjd_et As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' char * swe_get_planet_name(int ipl, char *spname);
Public Declare PtrSafe Function Native_swe_get_planet_name Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_planet_name" _
    ( _
        ByVal p_ipl As Long, _
        ByRef p_spname As Byte _
    ) As LongPtr

' double swe_get_tid_acc(void);
Public Declare PtrSafe Function Native_swe_get_tid_acc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_get_tid_acc" _
    () As Double

' EXPERIMENTAL / upstream internal: Upstream labels this API 'secret, for Victor Reijs'.
' int32 swe_heliacal_angle(double tjdut, double *dgeo, double *datm, double *dobs, int32 helflag, double mag, double azi_obj, double azi_sun, double azi_moon, double alt_moon, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_heliacal_angle Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_heliacal_angle" _
    ( _
        ByVal p_tjdut As Double, _
        ByRef p_dgeo As Double, _
        ByRef p_datm As Double, _
        ByRef p_dobs As Double, _
        ByVal p_helflag As Long, _
        ByVal p_mag As Double, _
        ByVal p_azi_obj As Double, _
        ByVal p_azi_sun As Double, _
        ByVal p_azi_moon As Double, _
        ByVal p_alt_moon As Double, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_heliacal_pheno_ut(double tjd_ut, double *geopos, double *datm, double *dobs, char *ObjectName, int32 TypeEvent, int32 helflag, double *darr, char *serr);
Public Declare PtrSafe Function Native_swe_heliacal_pheno_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_heliacal_pheno_ut" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByRef p_geopos As Double, _
        ByRef p_datm As Double, _
        ByRef p_dobs As Double, _
        ByRef p_ObjectName As Byte, _
        ByVal p_TypeEvent As Long, _
        ByVal p_helflag As Long, _
        ByRef p_darr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_heliacal_ut(double tjdstart_ut, double *geopos, double *datm, double *dobs, char *ObjectName, int32 TypeEvent, int32 iflag, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_heliacal_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_heliacal_ut" _
    ( _
        ByVal p_tjdstart_ut As Double, _
        ByRef p_geopos As Double, _
        ByRef p_datm As Double, _
        ByRef p_dobs As Double, _
        ByRef p_ObjectName As Byte, _
        ByVal p_TypeEvent As Long, _
        ByVal p_iflag As Long, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_helio_cross(int32 ipl, double x2cross, double jd_et, int32 iflag, int32 dir, double *jd_cross, char *serr);
Public Declare PtrSafe Function Native_swe_helio_cross Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_helio_cross" _
    ( _
        ByVal p_ipl As Long, _
        ByVal p_x2cross As Double, _
        ByVal p_jd_et As Double, _
        ByVal p_iflag As Long, _
        ByVal p_dir As Long, _
        ByRef p_jd_cross As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_helio_cross_ut(int32 ipl, double x2cross, double jd_ut, int32 iflag, int32 dir, double *jd_cross, char *serr);
Public Declare PtrSafe Function Native_swe_helio_cross_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_helio_cross_ut" _
    ( _
        ByVal p_ipl As Long, _
        ByVal p_x2cross As Double, _
        ByVal p_jd_ut As Double, _
        ByVal p_iflag As Long, _
        ByVal p_dir As Long, _
        ByRef p_jd_cross As Double, _
        ByRef p_serr As Byte _
    ) As Long

' const char * swe_house_name(int hsys);
Public Declare PtrSafe Function Native_swe_house_name Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_house_name" _
    ( _
        ByVal p_hsys As Long _
    ) As LongPtr

' double swe_house_pos(double armc, double geolat, double eps, int hsys, double *xpin, char *serr);
Public Declare PtrSafe Function Native_swe_house_pos Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_house_pos" _
    ( _
        ByVal p_armc As Double, _
        ByVal p_geolat As Double, _
        ByVal p_eps As Double, _
        ByVal p_hsys As Long, _
        ByRef p_xpin As Double, _
        ByRef p_serr As Byte _
    ) As Double

' int swe_houses(double tjd_ut, double geolat, double geolon, int hsys, double *cusps, double *ascmc);
Public Declare PtrSafe Function Native_swe_houses Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_houses" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_geolat As Double, _
        ByVal p_geolon As Double, _
        ByVal p_hsys As Long, _
        ByRef p_cusps As Double, _
        ByRef p_ascmc As Double _
    ) As Long

' int swe_houses_armc(double armc, double geolat, double eps, int hsys, double *cusps, double *ascmc);
Public Declare PtrSafe Function Native_swe_houses_armc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_houses_armc" _
    ( _
        ByVal p_armc As Double, _
        ByVal p_geolat As Double, _
        ByVal p_eps As Double, _
        ByVal p_hsys As Long, _
        ByRef p_cusps As Double, _
        ByRef p_ascmc As Double _
    ) As Long

' int swe_houses_armc_ex2(double armc, double geolat, double eps, int hsys, double *cusps, double *ascmc, double *cusp_speed, double *ascmc_speed, char *serr);
Public Declare PtrSafe Function Native_swe_houses_armc_ex2 Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_houses_armc_ex2" _
    ( _
        ByVal p_armc As Double, _
        ByVal p_geolat As Double, _
        ByVal p_eps As Double, _
        ByVal p_hsys As Long, _
        ByRef p_cusps As Double, _
        ByRef p_ascmc As Double, _
        ByRef p_cusp_speed As Double, _
        ByRef p_ascmc_speed As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int swe_houses_ex(double tjd_ut, int32 iflag, double geolat, double geolon, int hsys, double *cusps, double *ascmc);
Public Declare PtrSafe Function Native_swe_houses_ex Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_houses_ex" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_iflag As Long, _
        ByVal p_geolat As Double, _
        ByVal p_geolon As Double, _
        ByVal p_hsys As Long, _
        ByRef p_cusps As Double, _
        ByRef p_ascmc As Double _
    ) As Long

' int swe_houses_ex2(double tjd_ut, int32 iflag, double geolat, double geolon, int hsys, double *cusps, double *ascmc, double *cusp_speed, double *ascmc_speed, char *serr);
Public Declare PtrSafe Function Native_swe_houses_ex2 Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_houses_ex2" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_iflag As Long, _
        ByVal p_geolat As Double, _
        ByVal p_geolon As Double, _
        ByVal p_hsys As Long, _
        ByRef p_cusps As Double, _
        ByRef p_ascmc As Double, _
        ByRef p_cusp_speed As Double, _
        ByRef p_ascmc_speed As Double, _
        ByRef p_serr As Byte _
    ) As Long

' void swe_jdet_to_utc(double tjd_et, int32 gregflag, int32 *iyear, int32 *imonth, int32 *iday, int32 *ihour, int32 *imin, double *dsec);
Public Declare PtrSafe Sub Native_swe_jdet_to_utc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_jdet_to_utc" _
    ( _
        ByVal p_tjd_et As Double, _
        ByVal p_gregflag As Long, _
        ByRef p_iyear As Long, _
        ByRef p_imonth As Long, _
        ByRef p_iday As Long, _
        ByRef p_ihour As Long, _
        ByRef p_imin As Long, _
        ByRef p_dsec As Double _
    )

' void swe_jdut1_to_utc(double tjd_ut, int32 gregflag, int32 *iyear, int32 *imonth, int32 *iday, int32 *ihour, int32 *imin, double *dsec);
Public Declare PtrSafe Sub Native_swe_jdut1_to_utc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_jdut1_to_utc" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_gregflag As Long, _
        ByRef p_iyear As Long, _
        ByRef p_imonth As Long, _
        ByRef p_iday As Long, _
        ByRef p_ihour As Long, _
        ByRef p_imin As Long, _
        ByRef p_dsec As Double _
    )

' double swe_julday(int year, int month, int day, double hour, int gregflag);
Public Declare PtrSafe Function Native_swe_julday Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_julday" _
    ( _
        ByVal p_year As Long, _
        ByVal p_month As Long, _
        ByVal p_day As Long, _
        ByVal p_hour As Double, _
        ByVal p_gregflag As Long _
    ) As Double

' int32 swe_lat_to_lmt(double tjd_lat, double geolon, double *tjd_lmt, char *serr);
Public Declare PtrSafe Function Native_swe_lat_to_lmt Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lat_to_lmt" _
    ( _
        ByVal p_tjd_lat As Double, _
        ByVal p_geolon As Double, _
        ByRef p_tjd_lmt As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lmt_to_lat(double tjd_lmt, double geolon, double *tjd_lat, char *serr);
Public Declare PtrSafe Function Native_swe_lmt_to_lat Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lmt_to_lat" _
    ( _
        ByVal p_tjd_lmt As Double, _
        ByVal p_geolon As Double, _
        ByRef p_tjd_lat As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_eclipse_how(double tjd_ut, int32 ifl, double *geopos, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_lun_eclipse_how Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_eclipse_how" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_eclipse_when(double tjd_start, int32 ifl, int32 ifltype, double *tret, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_lun_eclipse_when Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_eclipse_when" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ifl As Long, _
        ByVal p_ifltype As Long, _
        ByRef p_tret As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_eclipse_when_loc(double tjd_start, int32 ifl, double *geopos, double *tret, double *attr, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_lun_eclipse_when_loc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_eclipse_when_loc" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_tret As Double, _
        ByRef p_attr As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_occult_when_glob(double tjd_start, int32 ipl, char *starname, int32 ifl, int32 ifltype, double *tret, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_lun_occult_when_glob Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_occult_when_glob" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_ifl As Long, _
        ByVal p_ifltype As Long, _
        ByRef p_tret As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_occult_when_loc(double tjd_start, int32 ipl, char *starname, int32 ifl, double *geopos, double *tret, double *attr, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_lun_occult_when_loc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_occult_when_loc" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_tret As Double, _
        ByRef p_attr As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_lun_occult_where(double tjd, int32 ipl, char *starname, int32 ifl, double *geopos, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_lun_occult_where Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_lun_occult_where" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' double swe_mooncross(double x2cross, double jd_et, int32 flag, char *serr);
Public Declare PtrSafe Function Native_swe_mooncross Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_mooncross" _
    ( _
        ByVal p_x2cross As Double, _
        ByVal p_jd_et As Double, _
        ByVal p_flag As Long, _
        ByRef p_serr As Byte _
    ) As Double

' double swe_mooncross_node(double jd_et, int32 flag, double *xlon, double *xlat, char *serr);
Public Declare PtrSafe Function Native_swe_mooncross_node Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_mooncross_node" _
    ( _
        ByVal p_jd_et As Double, _
        ByVal p_flag As Long, _
        ByRef p_xlon As Double, _
        ByRef p_xlat As Double, _
        ByRef p_serr As Byte _
    ) As Double

' double swe_mooncross_node_ut(double jd_ut, int32 flag, double *xlon, double *xlat, char *serr);
Public Declare PtrSafe Function Native_swe_mooncross_node_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_mooncross_node_ut" _
    ( _
        ByVal p_jd_ut As Double, _
        ByVal p_flag As Long, _
        ByRef p_xlon As Double, _
        ByRef p_xlat As Double, _
        ByRef p_serr As Byte _
    ) As Double

' double swe_mooncross_ut(double x2cross, double jd_ut, int32 flag, char *serr);
Public Declare PtrSafe Function Native_swe_mooncross_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_mooncross_ut" _
    ( _
        ByVal p_x2cross As Double, _
        ByVal p_jd_ut As Double, _
        ByVal p_flag As Long, _
        ByRef p_serr As Byte _
    ) As Double

' int32 swe_nod_aps(double tjd_et, int32 ipl, int32 iflag, int32 method, double *xnasc, double *xndsc, double *xperi, double *xaphe, char *serr);
Public Declare PtrSafe Function Native_swe_nod_aps Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_nod_aps" _
    ( _
        ByVal p_tjd_et As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByVal p_method As Long, _
        ByRef p_xnasc As Double, _
        ByRef p_xndsc As Double, _
        ByRef p_xperi As Double, _
        ByRef p_xaphe As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_nod_aps_ut(double tjd_ut, int32 ipl, int32 iflag, int32 method, double *xnasc, double *xndsc, double *xperi, double *xaphe, char *serr);
Public Declare PtrSafe Function Native_swe_nod_aps_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_nod_aps_ut" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByVal p_method As Long, _
        ByRef p_xnasc As Double, _
        ByRef p_xndsc As Double, _
        ByRef p_xperi As Double, _
        ByRef p_xaphe As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_orbit_max_min_true_distance(double tjd_et, int32 ipl, int32 iflag, double *dmax, double *dmin, double *dtrue, char *serr);
Public Declare PtrSafe Function Native_swe_orbit_max_min_true_distance Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_orbit_max_min_true_distance" _
    ( _
        ByVal p_tjd_et As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_dmax As Double, _
        ByRef p_dmin As Double, _
        ByRef p_dtrue As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_pheno(double tjd, int32 ipl, int32 iflag, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_pheno Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_pheno" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_pheno_ut(double tjd_ut, int32 ipl, int32 iflag, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_pheno_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_pheno_ut" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ipl As Long, _
        ByVal p_iflag As Long, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' double swe_rad_midp(double x1, double x0);
Public Declare PtrSafe Function Native_swe_rad_midp Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_rad_midp" _
    ( _
        ByVal p_x1 As Double, _
        ByVal p_x0 As Double _
    ) As Double

' double swe_radnorm(double x);
Public Declare PtrSafe Function Native_swe_radnorm Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_radnorm" _
    ( _
        ByVal p_x As Double _
    ) As Double

' double swe_refrac(double inalt, double atpress, double attemp, int32 calc_flag);
Public Declare PtrSafe Function Native_swe_refrac Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_refrac" _
    ( _
        ByVal p_inalt As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByVal p_calc_flag As Long _
    ) As Double

' double swe_refrac_extended(double inalt, double geoalt, double atpress, double attemp, double lapse_rate, int32 calc_flag, double *dret);
Public Declare PtrSafe Function Native_swe_refrac_extended Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_refrac_extended" _
    ( _
        ByVal p_inalt As Double, _
        ByVal p_geoalt As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByVal p_lapse_rate As Double, _
        ByVal p_calc_flag As Long, _
        ByRef p_dret As Double _
    ) As Double

' void swe_revjul(double jd, int gregflag, int *jyear, int *jmon, int *jday, double *jut);
Public Declare PtrSafe Sub Native_swe_revjul Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_revjul" _
    ( _
        ByVal p_jd As Double, _
        ByVal p_gregflag As Long, _
        ByRef p_jyear As Long, _
        ByRef p_jmon As Long, _
        ByRef p_jday As Long, _
        ByRef p_jut As Double _
    )

' int32 swe_rise_trans(double tjd_ut, int32 ipl, char *starname, int32 epheflag, int32 rsmi, double *geopos, double atpress, double attemp, double *tret, char *serr);
Public Declare PtrSafe Function Native_swe_rise_trans Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_rise_trans" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_epheflag As Long, _
        ByVal p_rsmi As Long, _
        ByRef p_geopos As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByRef p_tret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_rise_trans_true_hor(double tjd_ut, int32 ipl, char *starname, int32 epheflag, int32 rsmi, double *geopos, double atpress, double attemp, double horhgt, double *tret, char *serr);
Public Declare PtrSafe Function Native_swe_rise_trans_true_hor Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_rise_trans_true_hor" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_ipl As Long, _
        ByRef p_starname As Byte, _
        ByVal p_epheflag As Long, _
        ByVal p_rsmi As Long, _
        ByRef p_geopos As Double, _
        ByVal p_atpress As Double, _
        ByVal p_attemp As Double, _
        ByVal p_horhgt As Double, _
        ByRef p_tret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' EXPERIMENTAL / upstream internal: Upstream labels this API 'secret, for Dieter' for model testing.
' void swe_set_astro_models(char *samod, int32 iflag);
Public Declare PtrSafe Sub Native_swe_set_astro_models Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_astro_models" _
    ( _
        ByRef p_samod As Byte, _
        ByVal p_iflag As Long _
    )

' void swe_set_delta_t_userdef(double dt);
Public Declare PtrSafe Sub Native_swe_set_delta_t_userdef Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_delta_t_userdef" _
    ( _
        ByVal p_dt As Double _
    )

' void swe_set_ephe_path(const char *path);
Public Declare PtrSafe Sub Native_swe_set_ephe_path Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_ephe_path" _
    ( _
        ByRef p_path As Byte _
    )

' void swe_set_interpolate_nut(AS_BOOL do_interpolate);
Public Declare PtrSafe Sub Native_swe_set_interpolate_nut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_interpolate_nut" _
    ( _
        ByVal p_do_interpolate As Long _
    )

' void swe_set_jpl_file(const char *fname);
Public Declare PtrSafe Sub Native_swe_set_jpl_file Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_jpl_file" _
    ( _
        ByRef p_fname As Byte _
    )

' void swe_set_lapse_rate(double lapse_rate);
Public Declare PtrSafe Sub Native_swe_set_lapse_rate Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_lapse_rate" _
    ( _
        ByVal p_lapse_rate As Double _
    )

' void swe_set_sid_mode(int32 sid_mode, double t0, double ayan_t0);
Public Declare PtrSafe Sub Native_swe_set_sid_mode Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_sid_mode" _
    ( _
        ByVal p_sid_mode As Long, _
        ByVal p_t0 As Double, _
        ByVal p_ayan_t0 As Double _
    )

' void swe_set_tid_acc(double t_acc);
Public Declare PtrSafe Sub Native_swe_set_tid_acc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_tid_acc" _
    ( _
        ByVal p_t_acc As Double _
    )

' void swe_set_topo(double geolon, double geolat, double geoalt);
Public Declare PtrSafe Sub Native_swe_set_topo Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_set_topo" _
    ( _
        ByVal p_geolon As Double, _
        ByVal p_geolat As Double, _
        ByVal p_geoalt As Double _
    )

' double swe_sidtime(double tjd_ut);
Public Declare PtrSafe Function Native_swe_sidtime Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sidtime" _
    ( _
        ByVal p_tjd_ut As Double _
    ) As Double

' double swe_sidtime0(double tjd_ut, double eps, double nut);
Public Declare PtrSafe Function Native_swe_sidtime0 Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sidtime0" _
    ( _
        ByVal p_tjd_ut As Double, _
        ByVal p_eps As Double, _
        ByVal p_nut As Double _
    ) As Double

' int32 swe_sol_eclipse_how(double tjd, int32 ifl, double *geopos, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_sol_eclipse_how Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sol_eclipse_how" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_sol_eclipse_when_glob(double tjd_start, int32 ifl, int32 ifltype, double *tret, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_sol_eclipse_when_glob Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sol_eclipse_when_glob" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ifl As Long, _
        ByVal p_ifltype As Long, _
        ByRef p_tret As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_sol_eclipse_when_loc(double tjd_start, int32 ifl, double *geopos, double *tret, double *attr, int32 backward, char *serr);
Public Declare PtrSafe Function Native_swe_sol_eclipse_when_loc Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sol_eclipse_when_loc" _
    ( _
        ByVal p_tjd_start As Double, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_tret As Double, _
        ByRef p_attr As Double, _
        ByVal p_backward As Long, _
        ByRef p_serr As Byte _
    ) As Long

' int32 swe_sol_eclipse_where(double tjd, int32 ifl, double *geopos, double *attr, char *serr);
Public Declare PtrSafe Function Native_swe_sol_eclipse_where Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_sol_eclipse_where" _
    ( _
        ByVal p_tjd As Double, _
        ByVal p_ifl As Long, _
        ByRef p_geopos As Double, _
        ByRef p_attr As Double, _
        ByRef p_serr As Byte _
    ) As Long

' double swe_solcross(double x2cross, double jd_et, int32 flag, char *serr);
Public Declare PtrSafe Function Native_swe_solcross Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_solcross" _
    ( _
        ByVal p_x2cross As Double, _
        ByVal p_jd_et As Double, _
        ByVal p_flag As Long, _
        ByRef p_serr As Byte _
    ) As Double

' double swe_solcross_ut(double x2cross, double jd_ut, int32 flag, char *serr);
Public Declare PtrSafe Function Native_swe_solcross_ut Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_solcross_ut" _
    ( _
        ByVal p_x2cross As Double, _
        ByVal p_jd_ut As Double, _
        ByVal p_flag As Long, _
        ByRef p_serr As Byte _
    ) As Double

' void swe_split_deg(double ddeg, int32 roundflag, int32 *ideg, int32 *imin, int32 *isec, double *dsecfr, int32 *isgn);
Public Declare PtrSafe Sub Native_swe_split_deg Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_split_deg" _
    ( _
        ByVal p_ddeg As Double, _
        ByVal p_roundflag As Long, _
        ByRef p_ideg As Long, _
        ByRef p_imin As Long, _
        ByRef p_isec As Long, _
        ByRef p_dsecfr As Double, _
        ByRef p_isgn As Long _
    )

' int32 swe_time_equ(double tjd, double *te, char *serr);
Public Declare PtrSafe Function Native_swe_time_equ Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_time_equ" _
    ( _
        ByVal p_tjd As Double, _
        ByRef p_te As Double, _
        ByRef p_serr As Byte _
    ) As Long

' EXPERIMENTAL / upstream internal: Upstream labels this API 'secret, for Victor Reijs'.
' int32 swe_topo_arcus_visionis(double tjdut, double *dgeo, double *datm, double *dobs, int32 helflag, double mag, double azi_obj, double alt_obj, double azi_sun, double azi_moon, double alt_moon, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_topo_arcus_visionis Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_topo_arcus_visionis" _
    ( _
        ByVal p_tjdut As Double, _
        ByRef p_dgeo As Double, _
        ByRef p_datm As Double, _
        ByRef p_dobs As Double, _
        ByVal p_helflag As Long, _
        ByVal p_mag As Double, _
        ByVal p_azi_obj As Double, _
        ByVal p_alt_obj As Double, _
        ByVal p_azi_sun As Double, _
        ByVal p_azi_moon As Double, _
        ByVal p_alt_moon As Double, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' void swe_utc_time_zone(int32 iyear, int32 imonth, int32 iday, int32 ihour, int32 imin, double dsec, double d_timezone, int32 *iyear_out, int32 *imonth_out, int32 *iday_out, int32 *ihour_out, int32 *imin_out, double *dsec_out);
Public Declare PtrSafe Sub Native_swe_utc_time_zone Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_utc_time_zone" _
    ( _
        ByVal p_iyear As Long, _
        ByVal p_imonth As Long, _
        ByVal p_iday As Long, _
        ByVal p_ihour As Long, _
        ByVal p_imin As Long, _
        ByVal p_dsec As Double, _
        ByVal p_d_timezone As Double, _
        ByRef p_iyear_out As Long, _
        ByRef p_imonth_out As Long, _
        ByRef p_iday_out As Long, _
        ByRef p_ihour_out As Long, _
        ByRef p_imin_out As Long, _
        ByRef p_dsec_out As Double _
    )

' int32 swe_utc_to_jd(int32 iyear, int32 imonth, int32 iday, int32 ihour, int32 imin, double dsec, int32 gregflag, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_utc_to_jd Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_utc_to_jd" _
    ( _
        ByVal p_iyear As Long, _
        ByVal p_imonth As Long, _
        ByVal p_iday As Long, _
        ByVal p_ihour As Long, _
        ByVal p_imin As Long, _
        ByVal p_dsec As Double, _
        ByVal p_gregflag As Long, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long

' char * swe_version(char *);
Public Declare PtrSafe Function Native_swe_version Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_version" _
    ( _
        ByRef p_arg1 As Byte _
    ) As LongPtr

' int32 swe_vis_limit_mag(double tjdut, double *geopos, double *datm, double *dobs, char *ObjectName, int32 helflag, double *dret, char *serr);
Public Declare PtrSafe Function Native_swe_vis_limit_mag Lib "swexcel-se-2.10.3b-x64.dll" Alias "swe_vis_limit_mag" _
    ( _
        ByVal p_tjdut As Double, _
        ByRef p_geopos As Double, _
        ByRef p_datm As Double, _
        ByRef p_dobs As Double, _
        ByRef p_ObjectName As Byte, _
        ByVal p_helflag As Long, _
        ByRef p_dret As Double, _
        ByRef p_serr As Byte _
    ) As Long
